#All BACnet bitrsings type
service_supported_bs = {
   0 : "acknowledge-alarm",
   1 : "confirmed-cov-notification",
   2 : "confirmed-event-notification",
   3 : "get-alarm-summary",
   4 : "get-enrollment-summary",
   5 : "subscribe-cov",
   6 : "atomic-read-file",
   7 : "atomic-write-file",
   8 : "add-list-element",
   9 : "remove-list-element",
  10 : "create-object",
  11 : "delete-object",
  12 : "read-property",
  13 : "read-property-conditional",
  14 : "read-property-multiple",
  15 : "write-property",
  16 : "write-property-multiple",
  17 : "device-communication-control",
  18 : "confirmed-private-transfer",
  19 : "confirmed-text-message",
  20 : "reinitialize-device",
  21 : "vt-open",
  22 : "vt-close",
  23 : "vt-data",
  24 : "authenticate",
  25 : "request-key",
  26 : "i-am",
  27 : "i-have",
  28 : "unconfirmed-cov-notification",
  29 : "unconfirmed-event-notification",
  30 : "unconfirmed-private-transfer",
  31 : "unconfirmed-text-message",
  32 : "time-synchronization",
  33 : "who-has",
  34 : "who-is",
  35 : "read-range",
  36 : "utc-time-synchronization",
  37 : "life-safety-operation",
  38 : "subscribe-cov-property",
  39 : "get-event-information",
  40 : "write-group",
  41 : "subscribe-cov-property-multiple",
  42 : "confirmed-cov-notification-multipl",
  43 : "unconfirmed-cov-notification-multiple",
  44 : "confirmed-audit-notification",
  45 : "audit-log-query",
  46 : "unconfirmed-audit-notification",
  47 : "who-Am-I",
  48 : "you-Are",
  46 : "unconfirmed-audit-notification",
}
 
object_types_bs={
    0 : "analog-input",
    1 : "analog-output",
    2 : "analog-value",
    3 : "binary-input",
    4 : "binary-output",
    5 : "binary-value",
    6 : "calendar",
    7 : "command",
    8 : "device",
    9 : "event-enrollment",
    10 : "file",
    11 : "group",
    12 : " loop",
    13 : "multi-state-input",
    14 : "multi-state-output",
    15 : "notification-class",
    16 : "program",
    17 : "schedule",
    18 : "averaging",
    19 : "multi-state-value",
    20 : "trend-log",
    21 : "life-safety-point",
    22 : "life-safety-zone",
    23 : "accumulator",
    24 : "pulse-converter",
    25 : "event-log",
    26 : "global-group",
    27 : "trend-log-multiple",
    28 : "load-control",
    29 : "structured-view",
    30 : "access-door",
    31 : "timer",
    32 : "access-credential",
    33 : "access-point",
    34 : "access-rights",
    35 : "access-user",
    36 : "access-zone",
    37 : "credential-data-input",
    38 : "network-security (REMOVED)",
    39 : "bitstring-value",
    40 : "characterstring-value",
    41 : "datepattern-value",
    42 : "date-value",
    43 : "datetimepattern-value",
    44 : "datetime-value",
    45 : "integer-value",
    46 : "large-analog-value",
    47 : "octetstring-value",
    48 : "positive-integer-value",
    49 : "timepattern-value",
    50 : "time-value",
    51 : "notification-forwarder",
    52 : "alert-enrollment",
    53 : "channel",
    54 : "lighting-output",
    55 : "binary-lighting-output",
    56 : "network-port",
    57 : "elevator-group",
    58 : "escalator",
    59 : "lift",
    60 : "staging",
    61 : "audit-log",
    62 : "audit-reporter",
    63 : "custom-object1",
    64 : "custom-object2",
    65 : "custom-object3",
    66 : "custom-object4",
    67 : "custom-object5",
    68 : "custom-object6",
    69 : "custom-object7",
    70 : "custom-object8",
    71 : "custom-object9", 
}

status_flags_bs ={
  0 : "in-alarm",
  1 : "fault",
  2 : "overridden",
  3 : "out-of-service",
}

audit_operation_flag_bs = {
   0 : "read",
   1 : "write",
   2 : "create",
   3 : "delete",
   4 : "life-safety",
   5 : "acknowledge-alarm",
   6 : "device-disable-comm",
   7 : "device-enable-comm",
   8 : "device-reset",
   9 : "device-backup",
  10 : "device-restore",
  11 : "subscription",
  12 : "notification",
  13 : "auditing-failure",
  14 : "network-changes",
  15 : "general",
}

days_of_week_bs = {
  0 : "monday",
  1 : "tuesday",
  2 : "wednesday",
  3 : "thursday",
  4 : "friday",
  5 : "saturday",
  6 : "sunday",
}

event_transition_bs = {
  0 : "to-offnormal",
  1 : "to-fault",
  2 : "to-normal",
 }

limit_enable_bs = {
  0 : "low-limit-enable",
  1 : "high-limit-enable"
}

log_status_bs = {
  0 : "log-disabled",
  1 : "buffer-purged",
  2 : "log-interrupted",
}

priority_filter_bs = {
   0 : "manual-life-safety",
   1 : "automatic-life-safety",
   2 : "priority-3",
   3 : "priority-4",
   4 : "critical-equipment-controls",
   5 : "minimum-on-off",
   6 : "priority-7",
   7 : "manual-operator",
   8 : "priority-9",
   9 : "priority-10",
  10 : "priority-11",
  11 : "priority-12",
  12 : "priority-13",
  13 : "priority-14",
  14 : "priority-15",
  15 : "priority-16",
}



#Property associated with the bitstring they await
bitstring_by_property = {
  "protocol-services-supported" : service_supported_bs,
  "protocol-object-types-supported" : object_types_bs,
  "status-flags" : status_flags_bs,
  "auditable-operations" : audit_operation_flag_bs,
  "event-enable" : event_transition_bs,
  "acked-transition" : event_transition_bs,
  "limit-enable" : limit_enable_bs,
  "audit-priority-filter" : priority_filter_bs,
  "log-buffer" : log_status_bs
}