import csv
#All enum in Bacnet
reject_reason={
   0 : "other",
   1 : "buffer-overflow",
   2 : "inconsistent-parameters",
   3 : "invalid-parameter-data-type",
   4 : "invalid-tag",
   5 : "missing-required-parameter",
   6 : "parameter-out-of-range",
   7 : "too-many-arguments",
   8 : "undefined-enumeration",
   9 : "unrecognized-service",
  10 : "invalid-data-encoding",
}



object_types={
    0 : "analog-input",
    1 : "analog-output",
    2 : "analog-value",
    3 : "binary-input",
    4 : "binary-output",
    5 : "binary-value",
    6 : "calendar",
    7 : "command",
    8 : "device",
    9 : "event-enrollment",
    10 : "file",
    11 : "group",
    12 : "loop",
    13 : "multi-state-input",
    14 : "multi-state-output",
    15 : "notification-class",
    16 : "program",
    17 : "schedule",
    18 : "averaging",
    19 : "multi-state-value",
    20 : "trend-log",
    21 : "life-safety-point",
    22 : "life-safety-zone",
    23 : "accumulator",
    24 : "pulse-converter",
    25 : "event-log",
    26 : "global-group",
    27 : "trend-log-multiple",
    28 : "load-control",
    29 : "structured-view",
    30 : "access-door",
    31 : "timer",
    32 : "access-credential",
    33 : "access-point",
    34 : "access-rights",
    35 : "access-user",
    36 : "access-zone",
    37 : "credential-data-input",
    39 : "bitstring-value",
    40 : "characterstring-value",
    41 : "datepattern-value",
    42 : "date-value",
    43 : "datetimepattern-value",
    44 : "datetime-value",
    45 : "integer-value",
    46 : "large-analog-value",
    47 : "octetstring-value",
    48 : "positive-integer-value",
    49 : "timepattern-value",
    50 : "time-value",
    51 : "notification-forwarder",
    52 : "alert-enrollment",
    53 : "channel",
    54 : "lighting-output",
    55 : "binary-lighting-output",
    56 : "network-port",
    57 : "elevator-group",
    58 : "escalator",
    59 : "lift",
    60 : "staging",
    61 : "audit-log",
    62 : "audit-reporter",
}

object_types_emo = {
  "analog-input": "📊",
  "analog-output": "📊",
  "analog-value": "📊",
  "binary-input": "0️⃣ " ,
  "binary-output": "0️⃣ ",
  "binary-value": "0️⃣ ",
  "calendar": "📅",
  "command": "🎮",
  "device": "💻",
  "event-enrollment": "🗓 ",
  "file": "📂",
  "group": "👥",
  "loop": "🔄",
  "multi-state-input": "🔢",
  "multi-state-output": "🔢",
  "notification-class": "🔔",
  "program": "💾",
  "schedule": "⏳",
  "averaging": "📈",
  "multi-state-value": "🔢",
  "trend-log": "📈",
  "life-safety-point": "🏥",
  "life-safety-zone": "🏥",
  "accumulator": "📟",
  "pulse-converter": "🔁",
  "event-log": "📑",
  "global-group": "🌍",
  "trend-log-multiple": "📈",
  "load-control": "⚙️ ",
  "structured-view": "🔎",
  "access-door": "🚪",
  "timer": "⏰",
  "access-credential": "🔑",
  "access-point": "🚸",
  "access-rights": "📜",
  "access-user": "👤",
  "access-zone": "🔑",
  "credential-data-input": "🔑",
  "bitstring-value": "🔡",
  "characterstring-value": "🔡",
  "datepattern-value": "📆",
  "date-value": "📅",
  "datetimepattern-value": "🕐",
  "datetime-value": "⏰",
  "integer-value": "🔢",
  "large-analog-value": "📊",
  "octetstring-value": "🔡",
  "positive-integer-value": "➕",
  "timepattern-value": "⏳",
  "time-value": "⏰",
  "notification-forwarder": "📡",
  "alert-enrollment": "⚠️ ",
  "channel": "📺",
  "lighting-output": "💡",
  "binary-lighting-output": "💡",
  "network-port": "🌐",
  "elevator-group": "⬆️⬇️",
  "escalator": "⬆️⬇️",
  "lift": "⬆️⬇️",
  "staging": "🎭",
  "audit-log": "📋",
  "audit-reporter": "🕵️ ",
  "custom" : "🏗️ "
}


vendor_id = {
  0 : "ASHRAE",
  1 : "NIST",
  2 : "The Trane Company",
  3 : "McQuay International",
  4 : "PolarSoft",
  5 : "Johnson Controls Inc.",
  6 : "American Auto-Matrix",
  7 : "Siemens Schweiz AG (Formerly: Landis & Staefa Division Europe)",
  8 : "Delta Controls",
  9 : "Siemens Schweiz AG",
  10 : "Schneider Electric",
  11 : "TAC",
  12 : "Orion Analysis Corporation",
  13 : "Teletrol Systems Inc.",
  14 : "Cimetrics Technology",
  15 : "Cornell University",
  16 : "United Technologies Carrier",
  17 : "Honeywell Inc.",
  18 : "Alerton / Honeywell",
  19 : "TAC AB",
  20 : "Hewlett-Packard Company",
  21 : "Dorsette.s Inc.",
  22 : "Siemens Schweiz AG (Formerly: Cerberus AG)",
  23 : "York Controls Group",
  24 : "Automated Logic Corporation",
  25 : "CSI Control Systems International",
  26 : "Phoenix Controls Corporation",
  27 : "Innovex Technologies Inc.",
  28 : "KMC Controls Inc.",
  29 : "Xn Technologies Inc.",
  30 : "Hyundai Information Technology Co. Ltd.",
  31 : "Tokimec Inc.",
  32 : "Simplex",
  33 : "North Building Technologies Limited",
  34 : "Notifier",
  35 : "Reliable Controls Corporation",
  36 : "Tridium Inc.",
  37 : "Sierra Monitor Corporation/FieldServer Technologies",
  38 : "Silicon Energy",
  39 : "Kieback & Peter GmbH & Co KG",
  40 : "Anacon Systems Inc.",
  41 : "Systems Controls & Instruments LLC",
  42 : "Lithonia Lighting",
  43 : "Micropower Manufacturing",
  44 : "Matrix Controls",
  45 : "METALAIRE",
  46 : "ESS Engineering",
  47 : "Sphere Systems Pty Ltd.",
  48 : "Walker Technologies Corporation",
  49 : "H I Solutions Inc.",
  50 : "MBS GmbH",
  51 : "SAMSON AG",
  52 : "Badger Meter Inc.",
  53 : "DAIKIN Industries Ltd.",
  54 : "NARA Controls Inc.",
  55 : "Mammoth Inc.",
  56 : "Liebert Corporation",
  57 : "SEMCO Incorporated",
  58 : "Air Monitor Corporation",
  59 : "TRIATEK LLC",
  60 : "NexLight",
  61 : "Multistack",
  62 : "TSI Incorporated",
  63 : "Weather-Rite Inc.",
  64 : "Dunham-Bush",
  65 : "Reliance Electric",
  66 : "LCS Inc.",
  67 : "Regulator Australia PTY Ltd.",
  68 : "Touch-Plate Lighting Controls",
  69 : "Amann GmbH",
  70 : "RLE Technologies",
  71 : "Cardkey Systems",
  72 : "SECOM Co. Ltd.",
  73 : "ABB Gebäetechnik AG Bereich NetServ",
  74 : "KNX Association cvba",
  75 : "Institute of Electrical Installation Engineers of Japan (IEIEJ)",
  76 : "Nohmi Bosai Ltd.",
  77 : "Carel S.p.A.",
  78 : "AirSense Technology Inc.",
  79 : "Hochiki Corporation",
  80 : "Fr. Sauter AG",
  81 : "Matsushita Electric Works Ltd.",
  82 : "Mitsubishi Electric Corporation Inazawa Works",
  83 : "Mitsubishi Heavy Industries Ltd.",
  84 : "ITT Bell & Gossett",
  85 : "Yamatake Building Systems Co. Ltd.",
  86 : "The Watt Stopper Inc.",
  87 : "Aichi Tokei Denki Co. Ltd.",
  88 : "Activation Technologies LLC",
  89 : "Saia-Burgess Controls Ltd.",
  90 : "Hitachi Ltd.",
  91 : "Novar Corp./Trend Control Systems Ltd.",
  92 : "Mitsubishi Electric Lighting Corporation",
  93 : "Argus Control Systems Ltd.",
  94 : "Kyuki Corporation",
  95 : "Richards-Zeta Building Intelligence Inc.",
  96 : "Scientech R&D Inc.",
  97 : "VCI Controls Inc.",
  98 : "Toshiba Corporation",
  99 : "Mitsubishi Electric Corporation Air Conditioning & Refrigeration Systems Works",
  100 : "Custom Mechanical Equipment LLC",
  101 : "ClimateMaster",
  102 : "ICP Panel-Tec Inc.",
  103 : "D-Tek Controls",
  104 : "NEC Engineering Ltd.",
  105 : "PRIVA BV",
  106 : "Meidensha Corporation",
  107 : "JCI Systems Integration Services",
  108 : "Freedom Corporation",
  109 : "Neuberger Gebäeautomation GmbH",
  110 : "Sitronix",
  111 : "Leviton Manufacturing",
  112 : "Fujitsu Limited",
  113 : "Emerson Network Power",
  114 : "S. A. Armstrong Ltd.",
  115 : "Visonet AG",
  116 : "M&M Systems Inc.",
  117 : "Custom Software Engineering",
  118 : "Nittan Company Limited",
  119 : "Elutions Inc. (Wizcon Systems SAS)",
  120 : "Pacom Systems Pty. Ltd.",
  121 : "Unico Inc.",
  122 : "Ebtron Inc.",
  123 : "Scada Engine",
  124 : "AC Technology Corporation",
  125 : "Eagle Technology",
  126 : "Data Aire Inc.",
  127 : "ABB Inc.",
  128 : "Transbit Sp. z o. o.",
  129 : "Toshiba Carrier Corporation",
  130 : "Shenzhen Junzhi Hi-Tech Co. Ltd.",
  131 : "Tokai Soft",
  132 : "Blue Ridge Technologies",
  133 : "Veris Industries",
  134 : "Centaurus Prime",
  135 : "Sand Network Systems",
  136 : "Regulvar Inc.",
  137 : "AFDtek Division of Fastek International Inc.",
  138 : "PowerCold Comfort Air Solutions Inc.",
  139 : "I Controls",
  140 : "Viconics Electronics Inc.",
  141 : "Yaskawa America Inc.",
  142 : "DEOS control systems GmbH",
  143 : "Digitale Mess- und Steuersysteme AG",
  144 : "Fujitsu General Limited",
  145 : "Project Engineering S.r.l.",
  146 : "Sanyo Electric Co. Ltd.",
  147 : "Integrated Information Systems Inc.",
  148 : "Temco Controls Ltd.",
  149 : "Airtek International Inc.",
  150 : "Advantech Corporation",
  151 : "Titan Products Ltd.",
  152 : "Regel Partners",
  153 : "National Environmental Product",
  154 : "Unitec Corporation",
  155 : "Kanden Engineering Company",
  156 : "Messner Gebäetechnik GmbH",
  157 : "Integrated.CH",
  158 : "Price Industries",
  159 : "SE-Elektronic GmbH",
  160 : "Rockwell Automation",
  161 : "Enflex Corp.",
  162 : "ASI Controls",
  163 : "SysMik GmbH Dresden",
  164 : "HSC Regelungstechnik GmbH",
  165 : "Smart Temp Australia Pty. Ltd.",
  166 : "Cooper Controls",
  167 : "Duksan Mecasys Co. Ltd.",
  168 : "Fuji IT Co. Ltd.",
  169 : "Vacon Plc",
  170 : "Leader Controls",
  171 : "Cylon Controls Ltd.",
  172 : "Compas",
  173 : "Mitsubishi Electric Building Techno-Service Co. Ltd.",
  174 : "Building Control Integrators",
  175 : "ITG Worldwide (M) Sdn Bhd",
  176 : "Lutron Electronics Co. Inc.",
  178 : "LOYTEC Electronics GmbH",
  179 : "ProLon",
  180 : "Mega Controls Limited",
  181 : "Micro Control Systems Inc.",
  182 : "Kiyon Inc.",
  183 : "Dust Networks",
  184 : "Advanced Building Automation Systems",
  185 : "Hermos AG",
  186 : "CEZIM",
  187 : "Softing",
  188 : "Lynxspring",
  189 : "Schneider Toshiba Inverter Europe",
  190 : "Danfoss Drives A/S",
  191 : "Eaton Corporation",
  192 : "Matyca S.A.",
  193 : "Botech AB",
  194 : "Noveo Inc.",
  195 : "AMEV",
  196 : "Yokogawa Electric Corporation",
  197 : "GFR Gesellschaft füelungstechnik",
  198 : "Exact Logic",
  199 : "Mass Electronics Pty Ltd dba Innotech Control Systems Australia",
  200 : "Kandenko Co. Ltd.",
  201 : "DTF Daten-Technik Fries",
  202 : "Klimasoft Ltd.",
  203 : "Toshiba Schneider Inverter Corporation",
  204 : "Control Applications Ltd.",
  205 : "KDT Systems Co. Ltd.",
  206 : "Onicon Incorporated",
  207 : "Automation Displays Inc.",
  208 : "Control Solutions Inc.",
  209 : "Remsdaq Limited",
  210 : "NTT Facilities Inc.",
  211 : "VIPA GmbH",
  212 : "TSC21 Association of Japan",
  213 : "Strato Automation",
  214 : "HRW Limited",
  215 : "Lighting Control & Design Inc.",
  216 : "Mercy Electronic and Electrical Industries",
  217 : "Samsung SDS Co.Ltd",
  218 : "Impact Facility Solutions Inc.",
  219 : "Aircuity",
  220 : "Control Techniques Ltd.",
  221 : "OpenGeneral Pty. Ltd.",
  222 : "WAGO Kontakttechnik GmbH & Co. KG",
  223 : "Cerus Industrial",
  224 : "Chloride Power Protection Company",
  225 : "Computrols Inc.",
  226 : "Phoenix Contact GmbH & Co. KG",
  227 : "Grundfos Management A/S",
  228 : "Ridder Drive Systems",
  229 : "Soft Device SDN BHD",
  230 : "Integrated Control Technology Limited",
  231 : "AIRxpert Systems Inc.",
  232 : "Microtrol Limited",
  233 : "Red Lion Controls",
  234 : "Digital Electronics Corporation",
  235 : "Ennovatis GmbH",
  236 : "Serotonin Software Technologies Inc.",
  237 : "LS Industrial Systems Co. Ltd.",
  238 : "Square D Company",
  239 : "S Squared Innovations Inc.",
  240 : "Aricent Ltd.",
  241 : "EtherMetrics LLC",
  242 : "Industrial Control Communications Inc.",
  243 : "Paragon Controls Inc.",
  244 : "A. O. Smith Corporation",
  245 : "Contemporary Control Systems Inc.",
  246 : "Intesis Software SL",
  247 : "Ingenieurgesellschaft N. Hartleb mbH",
  248 : "Heat-Timer Corporation",
  249 : "Ingrasys Technology Inc.",
  250 : "Costerm Building Automation",
  251 : "WILO SE",
  252 : "Embedia Technologies Corp.",
  253 : "Technilog",
  254 : "HR Controls Ltd. & Co. KG",
  255 : "Lennox International Inc.",
  256 : "RK-Tec Rauchklappen-Steuerungssysteme GmbH & Co. KG",
  257 : "Thermomax Ltd.",
  258 : "ELCON Electronic Control Ltd.",
  259 : "Larmia Control AB",
  260 : "BACnet Stack at SourceForge",
  261 : "G4S Security Services A/S",
  262 : "Exor International S.p.A.",
  263 : "Cristal Controles",
  264 : "Regin AB",
  265 : "Dimension Software Inc.",
  266 : "SynapSense Corporation",
  267 : "Beijing Nantree Electronic Co. Ltd.",
  268 : "Camus Hydronics Ltd.",
  269 : "Kawasaki Heavy Industries Ltd.",
  270 : "Critical Environment Technologies",
  271 : "ILSHIN IBS Co. Ltd.",
  272 : "ELESTA Energy Control AG",
  273 : "KROPMAN Installatietechniek",
  274 : "Baldor Electric Company",
  275 : "INGA mbH",
  276 : "GE Consumer & Industrial",
  277 : "Functional Devices Inc.",
  278 : "ESAC",
  279 : "M-System Co. Ltd.",
  280 : "Yokota Co. Ltd.",
  281 : "Hitranse Technology Co.LTD",
  282 : "Federspiel Controls",
  283 : "Kele Inc.",
  284 : "Opera Electronics Inc.",
  285 : "Gentec",
  286 : "Embedded Science Labs LLC",
  287 : "Parker Hannifin Corporation",
  288 : "MaCaPS International Limited",
  289 : "Link4 Corporation",
  290 : "Romutec Steuer-u. Regelsysteme GmbH",
  291 : "Pribusin Inc.",
  292 : "Advantage Controls",
  293 : "Critical Room Control",
  294 : "LEGRAND",
  295 : "Tongdy Control Technology Co. Ltd.",
  296 : "ISSARO Integrierte Systemtechnik",
  297 : "Pro-Dev Industries",
  298 : "DRI-STEEM",
  299 : "Creative Electronic GmbH",
  300 : "Swegon AB",
  301 : "Jan Brachacek",
  302 : "Hitachi Appliances Inc.",
  303 : "Real Time Automation Inc.",
  304 : "ITEC Hankyu-Hanshin Co.",
  305 : "Cyrus E&M Engineering Co. Ltd.",
  306 : "Racine Federated Inc.",
  307 : "Cirrascale Corporation",
  308 : "Elesta GmbH Building Automation",
  309 : "Securiton",
  310 : "OSlsoft Inc.",
  311 : "Hanazeder Electronic GmbH",
  312 : "Honeywell Security DeutschlandNovar GmbH",
  313 : "Siemens Energy & Automation Inc.",
  314 : "ETM Professional Control GmbH",
  315 : "Meitav-tec Ltd.",
  316 : "Janitza Electronics GmbH",
  317 : "MKS Nordhausen",
  318 : "De Gier Drive Systems B.V.",
  319 : "Cypress Envirosystems",
  320 : "SMARTron s.r.o.",
  321 : "Verari Systems Inc.",
  322 : "K-W Electronic Service Inc.",
  323 : "ALFA-SMART Energy Management",
  324 : "Telkonet Inc.",
  325 : "Securiton GmbH",
  326 : "Cemtrex Inc.",
  327 : "Performance Technologies Inc.",
  328 : "Xtralis (Aust) Pty Ltd",
  329 : "TROX GmbH",
  330 : "Beijing Hysine Technology Co.Ltd",
  331 : "RCK Controls Inc.",
  332 : "Distech Controls SAS",
  333 : "Novar/Honeywell",
  334 : "The S4 Group Inc.",
  335 : "Schneider Electric",
  336 : "LHA Systems",
  337 : "GHM engineering Group Inc.",
  338 : "Cllimalux S.A.",
  339 : "VAISALA Oyj",
  340 : "COMPLEX (Beijing) TechnologyCo. Ltd.",
  341 : "SCADAmetrics",
  342 : "POWERPEG NSI Limited",
  343 : "BACnet Interoperability Testing Services Inc.",
  344 : "Teco a.s.",
  345 : "Plexus Technology Inc.",
  346 : "Energy Focus Inc.",
  347 : "Powersmiths International Corp.",
  348 : "Nichibei Co. Ltd.",
  349 : "HKC Technology Ltd.",
  350 : "Ovation Networks Inc.",
  351 : "Setra Systems",
  352 : "AVG Automation",
  353 : "ZXC Ltd.",
  354 : "Byte Sphere",
  355 : "Generiton Co. Ltd.",
  356 : "Holter Regelarmaturen GmbH & Co. KG",
  357 : "Bedford Instruments LLC",
  358 : "Standair Inc.",
  359 : "WEG Automation - R&D",
  360 : "Prolon Control Systems ApS",
  361 : "Inneasoft",
  362 : "ConneXSoft GmbH",
  363 : "CEAG Notlichtsysteme GmbH",
  364 : "Distech Controls Inc.",
  365 : "Industrial Technology Research Institute",
  366 : "ICONICS Inc.",
  367 : "IQ Controls s.c.",
  368 : "OJ Electronics A/S",
  369 : "Rolbit Ltd.",
  370 : "Synapsys Solutions Ltd.",
  371 : "ACME Engineering Prod. Ltd.",
  372 : "Zener Electric Pty Ltd.",
  373 : "Selectronix Inc.",
  374 : "Gorbet & Banerjee LLC.",
  375 : "IME",
  376 : "Stephen H. Dawson Computer Service",
  377 : "Accutrol LLC",
  378 : "Schneider Elektronik GmbH",
  379 : "Alpha-Inno Tec GmbH",
  380 : "ADMMicro Inc.",
  381 : "Greystone Energy Systems Inc.",
  382 : "CAP Technologie",
  383 : "KeRo Systems",
  384 : "Domat Control System s.r.o.",
  385 : "Efektronics Pty. Ltd.",
  386 : "Hekatron Vertriebs GmbH",
  387 : "Securiton AG",
  388 : "Carlo Gavazzi Controls SpA",
  389 : "Chipkin Automation Systems",
  390 : "Savant Systems LLC",
  391 : "Simmtronic Lighting Controls",
  392 : "Abelko Innovation AB",
  393 : "Seresco Technologies Inc.",
  394 : "IT Watchdogs",
  395 : "Automation Assist Japan Corp.",
  396 : "Thermokon Sensortechnik GmbH",
  397 : "EGauge Systems LLC",
  398 : "Quantum Automation (ASIA) PTE Ltd.",
  399 : "Toshiba Lighting & Technology Corp.",
  400 : "SPIN Engenharia de Automaç Ltda.",
  401 : "Logistics Systems & Software Services India PVT. Ltd.",
  402 : "Delta Controls Integration Products",
  403 : "Focus Media",
  404 : "LUMEnergi Inc.",
  405 : "Kara Systems",
  406 : "RF Code Inc.",
  407 : "Fatek Automation Corp.",
  408 : "JANDA Software Company LLC",
  409 : "Open System Solutions Limited",
  410 : "Intelec Systems PTY Ltd.",
  411 : "Ecolodgix LLC",
  412 : "Douglas Lighting Controls",
  413 : "iSAtech GmbH",
  414 : "AREAL",
  415 : "Beckhoff Automation GmbH",
  416 : "IPAS GmbH",
  417 : "KE2 Therm Solutions",
  418 : "Base2Products",
  419 : "DTL Controls LLC",
  420 : "INNCOM International Inc.",
  421 : "BTR Netcom GmbH",
  422 : "Greentrol AutomationInc",
  423 : "BELIMO Automation AG",
  424 : "Samsung Heavy Industries CoLtd",
  425 : "Triacta Power Technologies Inc.",
  426 : "Globestar Systems",
  427 : "MLB Advanced MediaLP",
  428 : "SWG Stuckmann Wirtschaftliche Gebäesysteme GmbH",
  429 : "SensorSwitch",
  430 : "Multitek Power Limited",
  431 : "Aquametro AG",
  432 : "LG Electronics Inc.",
  433 : "Electronic Theatre Controls Inc.",
  434 : "Mitsubishi Electric Corporation Nagoya Works",
  435 : "Delta Electronics Inc.",
  436 : "Elma Kurtalj Ltd.",
  437 : "ADT Fire and Security Sp. A.o.o.",
  438 : "Nedap Security Management",
  439 : "ESC Automation Inc.",
  440 : "DSP4YOU Ltd.",
  441 : "GE Sensing and Inspection Technologies",
  442 : "Embedded Systems SIA",
  443 : "BEFEGA GmbH",
  444 : "Baseline Inc.",
  445 : "M2M Systems Integrators",
  446 : "OEMCtrl",
  447 : "Clarkson Controls Limited",
  448 : "Rogerwell Control System Limited",
  449 : "SCL Elements",
  450 : "Hitachi Ltd.",
  451 : "Newron System SA",
  452 : "BEVECO Gebouwautomatisering BV",
  453 : "Streamside Solutions",
  454 : "Yellowstone Soft",
  455 : "Oztech Intelligent Systems Pty Ltd.",
  456 : "Novelan GmbH",
  457 : "Flexim Americas Corporation",
  458 : "ICP DAS Co. Ltd.",
  459 : "CARMA Industries Inc.",
  460 : "Log-One Ltd.",
  461 : "TECO Electric & Machinery Co. Ltd.",
  462 : "ConnectEx Inc.",
  463 : "Turbo DDC Sü",
  464 : "Quatrosense Environmental Ltd.",
  465 : "Fifth Light Technology Ltd.",
  466 : "Scientific Solutions Ltd.",
  467 : "Controller Area Network Solutions (M) Sdn Bhd",
  468 : "RESOL - Elektronische Regelungen GmbH",
  469 : "RPBUS LLC",
  470 : "BRS Sistemas Eletronicos",
  471 : "WindowMaster A/S",
  472 : "Sunlux Technologies Ltd.",
  473 : "Measurlogic",
  474 : "Frimat GmbH",
  475 : "Spirax Sarco",
  476 : "Luxtron",
  477 : "Raypak Inc",
  478 : "Air Monitor Corporation",
  479 : "Regler Och Webbteknik Sverige (ROWS)",
  480 : "Intelligent Lighting Controls Inc.",
  481 : "Sanyo Electric Industry Co.Ltd",
  482 : "E-Mon Energy Monitoring Products",
  483 : "Digital Control Systems",
  484 : "ATI Airtest Technologies Inc.",
  485 : "SCS SA",
  486 : "HMS Industrial Networks AB",
  487 : "Shenzhen Universal Intellisys Co Ltd",
  488 : "EK Intellisys Sdn Bhd",
  489 : "SysCom",
  490 : "Firecom Inc.",
  491 : "ESA Elektroschaltanlagen Grimma GmbH",
  492 : "Kumahira Co Ltd",
  493 : "Hotraco",
  494 : "SABO Elektronik GmbH",
  495 : "Equip'Trans",
  496 : "TCS Basys Controls",
  497 : "FlowCon International A/S",
  498 : "ThyssenKrupp Elevator Americas",
  499 : "Abatement Technologies",
  500 : "Continental Control Systems LLC",
  501 : "WISAG Automatisierungstechnik GmbH & Co KG",
  502 : "EasyIO",
  503 : "EAP-Electric GmbH",
  504 : "Hardmeier",
  505 : "Mircom Group of Companies",
  506 : "Quest Controls",
  507 : "MestekInc",
  508 : "Pulse Energy",
  509 : "Tachikawa Corporation",
  510 : "University of Nebraska-Lincoln",
  511 : "Redwood Systems",
  512 : "PASStec Industrie-Elektronik GmbH",
  513 : "NgEK Inc.",
  514 : "FAW Electronics Ltd",
  515 : "Jireh Energy Tech Co. Ltd.",
  516 : "Enlighted Inc.",
  517 : "El-Piast Sp. Z o.o",
  518 : "NetxAutomation Software GmbH",
  519 : "Invertek Drives",
  520 : "Deutschmann Automation GmbH & Co. KG",
  521 : "EMU Electronic AG",
  522 : "Phaedrus Limited",
  523 : "Sigmatek GmbH & Co KG",
  524 : "Marlin Controls",
  525 : "CircutorSA",
  526 : "UTC Fire & Security",
  527 : "DENT Instruments Inc.",
  528 : "FHP Manufacturing Company - Bosch Group",
  529 : "GE Intelligent Platforms",
  530 : "Inner Range Pty Ltd",
  531 : "GLAS Energy Technology",
  532 : "MSR-Electronic-GmbH",
  533 : "Energy Control Systems Inc.",
  534 : "EMT Controls",
  535 : "Daintree Networks Inc.",
  536 : "EURO ICC d.o.o",
  537 : "TE Connectivity Energy",
  538 : "GEZE GmbH",
  539 : "NEC Corporation",
  540 : "Ho Cheung International Company Limited",
  541 : "Sharp Manufacturing Systems Corporation",
  542 : "DOT CONTROLS a.s.",
  543 : "BeaconMedæ0220",
  544 : "Midea Commercial Aircon",
  545 : "WattMaster Controls",
  546 : "Kamstrup A/S",
  547 : "CA Computer Automation GmbH",
  548 : "Laars Heating Systems Company",
  549 : "Hitachi Systems Ltd.",
  550 : "Fushan AKE Electronic Engineering Co. Ltd.",
  551 : "Toshiba International Corporation",
  552 : "Starman Systems LLC",
  553 : "Samsung Techwin Co. Ltd.",
  554 : "ISAS-Integrated Switchgear and Systems P/L",
  556 : "Obvius",
  557 : "Marek Guzik",
  558 : "Vortek Instruments LLC",
  559 : "Universal Lighting Technologies",
  560 : "Myers Power Products Inc.",
  561 : "Vector Controls GmbH",
  562 : "Crestron Electronics Inc.",
  563 : "A&E Controls Limited",
  564 : "Projektomontaza A.D.",
  565 : "Freeaire Refrigeration",
  566 : "Aqua Cooler Pty Limited",
  567 : "Basic Controls",
  568 : "GE Measurement and Control Solutions Advanced Sensors",
  569 : "EQUAL Networks",
  570 : "Millennial Net",
  571 : "APLI Ltd",
  572 : "Electro Industries/GaugeTech",
  573 : "SangMyung University",
  574 : "Coppertree Analytics Inc.",
  575 : "CoreNetiX GmbH",
  576 : "Acutherm",
  577 : "Dr. Riedel Automatisierungstechnik GmbH",
  578 : "Shina System Co.Ltd",
  579 : "Iqapertus",
  580 : "PSE Technology",
  581 : "BA Systems",
  582 : "BTICINO",
  583 : "Monico Inc.",
  584 : "iCue",
  585 : "tekmar Control Systems Ltd.",
  586 : "Control Technology Corporation",
  587 : "GFAE GmbH",
  588 : "BeKa Software GmbH",
  589 : "Isoil Industria SpA",
  590 : "Home Systems Consulting SpA",
  591 : "Socomec",
  592 : "Everex Communications Inc.",
  593 : "Ceiec Electric Technology",
  594 : "Atrila GmbH",
  595 : "WingTechs",
  596 : "Shenzhen Mek Intellisys Pte Ltd.",
  597 : "Nestfield Co. Ltd.",
  598 : "Swissphone Telecom AG",
  599 : "PNTECH JSC",
  600 : "Horner APG LLC",
  601 : "PVI Industries LLC",
  602 : "Ela-compil",
  603 : "Pegasus Automation International LLC",
  604 : "Wight Electronic Services Ltd.",
  605 : "Marcom",
  606 : "Exhausto A/S",
  607 : "Dwyer Instruments Inc.",
  608 : "Link GmbH",
  609 : "Oppermann Regelgerate GmbH",
  610 : "NuAire Inc.",
  611 : "Nortec Humidity Inc.",
  612 : "Bigwood Systems Inc.",
  613 : "Enbala Power Networks",
  614 : "Inter Energy Co. Ltd.",
  615 : "ETC",
  616 : "COMELEC S.A.R.L",
  617 : "Pythia Technologies",
  618 : "TrendPoint Systems Inc.",
  619 : "AWEX",
  620 : "Eurevia",
  621 : "Kongsberg E-lon AS",
  622 : "FlaktWoods",
  623 : "E + E Elektronik GES M.B.H.",
  624 : "ARC Informatique",
  625 : "SKIDATA AG",
  626 : "WSW Solutions",
  627 : "Trefon Electronic GmbH",
  628 : "Dongseo System",
  629 : "Kanontec Intelligence Technology Co. Ltd.",
  630 : "EVCO S.p.A.",
  631 : "Accuenergy (CANADA) Inc.",
  632 : "SoftDEL",
  633 : "Orion Energy Systems Inc.",
  634 : "Roboticsware",
  635 : "DOMIQ Sp. z o.o.",
  636 : "Solidyne",
  637 : "Elecsys Corporation",
  638 : "Conditionaire International Pty. Limited",
  639 : "Quebec Inc.",
  640 : "Homerun Holdings",
  641 : "RFM Inc.",
  642 : "Comptek",
  643 : "Westco Systems Inc.",
  644 : "Advancis Software & Services GmbH",
  645 : "Intergrid LLC",
  646 : "Markerr Controls Inc.",
  647 : "Toshiba Elevator and Building Systems Corporation",
  648 : "Spectrum Controls Inc.",
  649 : "Mkservice",
  650 : "Fox Thermal Instruments",
  651 : "SyxthSense Ltd",
  652 : "DUHA System S R.O.",
  653 : "NIBE",
  654 : "Melink Corporation",
  655 : "Fritz-Haber-Institut",
  656 : "MTU Onsite Energy GmbHGas Power Systems",
  657 : "Omega Engineering Inc.",
  658 : "Avelon",
  659 : "Ywire Technologies Inc.",
  660 : "M.R. Engineering Co. Ltd.",
  661 : "Lochinvar LLC",
  662 : "Sontay Limited",
  663 : "GRUPA Slawomir Chelminski",
  664 : "Arch Meter Corporation",
  665 : "Senva Inc.",
  667 : "FM-Tec",
  668 : "Systems Specialists Inc.",
  669 : "SenseAir",
  670 : "AB IndustrieTechnik Srl",
  671 : "Cortland Research LLC",
  672 : "MediaView",
  673 : "VDA Elettronica",
  674 : "CSS Inc.",
  675 : "Tek-Air Systems Inc.",
  676 : "ICDT",
  677 : "The Armstrong Monitoring Corporation",
  678 : "DIXELL S.r.l",
  679 : "Lead System Inc.",
  680 : "ISM EuroCenter S.A.",
  681 : "TDIS",
  682 : "Trade FIDES",
  683 : "KnübH (Emerson Network Power)",
  684 : "Resource Data Management",
  685 : "Abies Technology Inc.",
  686 : "Amalva",
  687 : "MIRAE Electrical Mfg. Co. Ltd.",
  688 : "HunterDouglas Architectural Projects Scandinavia ApS",
  689 : "RUNPAQ Group Co.Ltd",
  690 : "Unicard SA",
  691 : "IE Technologies",
  692 : "Ruskin Manufacturing",
  693 : "Calon Associates Limited",
  694 : "Contec Co. Ltd.",
  695 : "iT GmbH",
  696 : "Autani Corporation",
  697 : "Christian Fortin",
  698 : "HDL",
  699 : "IPID Sp. Z.O.O Limited",
  700 : "Fuji Electric Co.Ltd",
  701 : "View Inc.",
  702 : "Samsung S1 Corporation",
  703 : "New Lift",
  704 : "VRT Systems",
  705 : "Motion Control Engineering Inc.",
  706 : "Weiss Klimatechnik GmbH",
  707 : "Elkon",
  708 : "Eliwell Controls S.r.l.",
  709 : "Japan Computer Technos Corp",
  710 : "Rational Network ehf",
  711 : "Magnum Energy Solutions LLC",
  712 : "MelRok",
  713 : "VAE Group",
  714 : "LGCNS",
  715 : "Berghof Automationstechnik GmbH",
  716 : "Quark Communications Inc.",
  717 : "Sontex",
  718 : "mivune AG",
  719 : "Panduit",
  720 : "Smart Controls LLC",
  721 : "Compu-Aire Inc.",
  722 : "Sierra",
  723 : "ProtoSense Technologies",
  724 : "Eltrac Technologies Pvt Ltd",
  725 : "Bektas Invisible Controls GmbH",
  726 : "Entelec",
  727 : "Innexiv",
  728 : "Covenant",
  729 : "Davitor AB",
  730 : "TongFang Technovator",
  731 : "Building Robotics",
  732 : "HSS-MSR UG",
  733 : "FramTack LLC",
  734 : "B. L. Acoustics",
  735 : "Traxxon Rock Drills",
  736 : "Franke",
  737 : "Wurm GmbH & Co",
  738 : "AddENERGIE",
  739 : "Mirle Automation Corporation",
  740 : "Ibis Networks",
  741 : "ID-KARTA s.r.o.",
  742 : "Anaren",
  743 : "Span",
  744 : "Bosch Thermotechnology Corp",
  745 : "DRC Technology S.A.",
  746 : "Shanghai Energy Building Technology Co",
  747 : "Fraport AG",
  748 : "Flowgroup",
  749 : "Skytron Energy",
  750 : "ALTEL Wicha",
  751 : "Drupal",
  752 : "Axiomatic Technology",
  753 : "Bohnke + Partner",
  754 : "Function 1",
  755 : "Optergy Pty",
  756 : "LSI Virticus",
  757 : "Konzeptpark GmbH",
  758 : "Hubbell Building Automation",
  759 : "eCurv",
  760 : "Agnosys GmbH",
  761 : "Shanghai Sunfull Automation Co.",
  762 : "Kurz Instruments",
  763 : "Cias Elettronica S.r.l.",
  764 : "Multiaqua",
  765 : "BlueBox",
  766 : "Sensidyne",
  767 : "Viessmann Elektronik GmbH",
  768 : "ADFweb.com srl",
  769 : "Gaylord Industries",
  770 : "Majur Ltd.",
  771 : "Shanghai Huilin Technology Co.",
  772 : "Exotronic",
  773 : "Safecontrol spol s.r.o.",
  774 : "Amatis",
  775 : "Universal Electric Corporation",
  776 : "iBACnet",
  778 : "Smartrise Engineering",
  779 : "Miratron",
  780 : "SmartEdge",
  781 : "Mitsubishi Electric Australia Pty Ltd",
  782 : "Triangle Research International Ptd Ltd",
  783 : "Produal Oy",
  784 : "Milestone Systems A/S",
  785 : "Trustbridge",
  786 : "Feedback Solutions",
  787 : "IES",
  788 : "GE Critical Power",
  789 : "Riptide IO",
  790 : "Messerschmitt Systems AG",
  791 : "Dezem Energy Controlling",
  792 : "MechoSystems",
  793 : "evon GmbH",
  794 : "CS Lab GmbH",
  795 : "8760 Enterprises",
  796 : "Touche Controls",
  797 : "Ontrol Teknik Malzeme San. ve Tic. A.S.",
  798 : "Uni Control System Sp. Z o.o.",
  799 : "Weihai Ploumeter Co.",
  800 : "Elcom International Pvt. Ltd",
  801 : "Philips Lighting",
  802 : "AutomationDirect",
  803 : "Paragon Robotics",
  804 : "SMT System & Modules Technology AG",
  805 : "OS Technology Service and Trading Co.",
  806 : "CMR Controls Ltd",
  807 : "Innovari",
  808 : "ABB Control Products",
  809 : "Gesellschaft fur Gebaudeautomation mbH",
  810 : "RODI Systems Corp.",
  811 : "Nextek Power Systems",
  812 : "Creative Lighting",
  813 : "WaterFurnace International",
  814 : "Mercury Security",
  815 : "Hisense (Shandong) Air-Conditioning Co.",
  816 : "Layered Solutions",
  817 : "Leegood Automatic System",
  818 : "Shanghai Restar Technology Co.",
  819 : "Reimann Ingenieurburo",
  820 : "LynTec",
  821 : "HTP",
  822 : "Elkor Technologies",
  823 : "Bentrol Pty Ltd",
  824 : "Team-Control Oy",
  825 : "NextDevice",
  826 : "GLOBAL CONTROL 5 Sp. z o.o.",
  827 : "King I Electronics Co.",
  828 : "SAMDAV",
  829 : "Next Gen Industries Pvt. Ltd.",
  830 : "Entic LLC",
  831 : "ETAP",
  832 : "Moralle Electronics Limited",
  833 : "Leicom AG",
  834 : "Watts Regulator Company",
  835 : "S.C. Orbtronics S.R.L.",
  836 : "Gaussan Technologies",
  837 : "WEBfactory GmbH",
  838 : "Ocean Controls",
  839 : "Messana  Air-Ray Conditioning s.r.l.",
  840 : "Hangzhou BATOWN Technology Co. Ltd.",
  841 : "Reasonable Controls",
  842 : "Servisys",
  843 : "halstrup-walcher GmbH",
  844 : "SWG Automation Fuzhou Limited",
  845 : "KSB Aktiengesellschaft",
  846 : "Hybryd Sp. z o.o.",
  847 : "Helvatron AG",
  848 : "Oderon Sp. Z.O.O.",
  849 : "miko",
  850 : "Exodraft",
  851 : "Hochhuth GmbH",
  852 : "Integrated System Technologies Ltd.",
  853 : "Shanghai Cellcons Controls Co., Ltd",
  854 : "Emme Controls, LLC",
  855 : "Field Diagnostic Services, Inc.",
  856 : "Ges Teknik A.S.",
  857 : "Global Power Products, Inc.",
  858 : "Option NV",
  859 : "BV-Control AG",
  860 : "Sigren Engineering AG",
  861 : "Shanghai Jaltone Technology Co., Ltd.",
  862 : "MaxLine Solutions Ltd",
  863 : "Kron Instrumentos Elétricos Ltda",
  864 : "Thermo Matrix",
  865 : "Infinite Automation Systems, Inc.",
  866 : "Vantage",
  867 : "Elecon Measurements Pvt Ltd",
  868 : "TBA",
  869 : "Carnes Company",
  870 : "Harman Professional",
  871 : "Nenutec Asia Pacific Pte Ltd",
  872 : "Gia NV",
  873 : "Kepware Tehnologies",
  874 : "Temperature Electronics Ltd",
  875 : "Packet Power",
  876 : "Project Haystack Corporation",
  877 : "DEOS Controls Americas Inc.",
  878 : "Senseware Inc",
  879 : "MST Systemtechnik AG",
  880 : "Lonix Ltd",
  881 : "GMC-I Messtechnik GmbH",
  882 : "Aviosys International Inc.",
  883 : "Efficient Building Automation Corp.",
  884 : "Accutron Instruments Inc.",
  885 : "Vermont Energy Control Systems LLC",
  886 : "DCC Dynamics",
  887 : "B.E.G. Brück Electronic GmbH",
  889 : "NGBS Hungary Ltd.",
  890 : "ILLUM Technology, LLC",
  891 : "Delta Controls Germany Limited",
  892 : "S+T Service & Technique S.A.",
  893 : "SimpleSoft",
  894 : "Altair Engineering",
  895 : "EZEN Solution Inc.",
  896 : "Fujitec Co. Ltd.",
  897 : "Terralux",
  898 : "Annicom",
  899 : "Bihl+Wiedemann GmbH",
  900 : "Draper, Inc.",
  901 : "Schüco International KG",
  902 : "Otis Elevator Company",
  903 : "Fidelix Oy",
  904 : "RAM GmbH Mess- und Regeltechnik",
  905 : "WEMS",
  906 : "Ravel Electronics Pvt Ltd",
  907 : "OmniMagni",
  908 : "Echelon",
  909 : "Intellimeter Canada, Inc.",
  910 : "Bithouse Oy",
  912 : "BuildPulse",
  913 : "Shenzhen 1000 Building Automation Co. Ltd",
  914 : "AED Engineering GmbH",
  915 : "Güntner GmbH & Co. KG",
  916 : "KNXlogic",
  917 : "CIM Environmental Group",
  918 : "Flow Control",
  919 : "Lumen Cache, Inc.",
  920 : "Ecosystem",
  921 : "Potter Electric Signal Company, LLC",
  922 : "Tyco Fire & Security S.p.A.",
  923 : "Watanabe Electric Industry Co., Ltd.",
  924 : "Causam Energy",
  925 : "W-tec AG",
  926 : "IMI Hydronic Engineering International SA",
  927 : "ARIGO Software",
  928 : "MSA Safety",
  929 : "Smart Solucoes Ltda - MERCATO",
  930 : "PIATRA Engineering",
  931 : "ODIN Automation Systems, LLC",
  932 : "Belparts NV",
  933 : "UAB, SALDA",
  934 : "Alre-IT Regeltechnik GmbH",
  935 : "Ingenieurbüro H. Lertes GmbH & Co. KG",
  936 : "Breathing Buildings",
  937 : "eWON SA",
  938 : "Cav. Uff. Giacomo Cimberio S.p.A",
  939 : "PKE Electronics AG",
  940 : "Allen",
  941 : "Kastle Systems",
  942 : "Logical Electro-Mechanical (EM) Systems, Inc.",
  943 : "ppKinetics Instruments, LLC",
  944 : "Cathexis Technologies",
  945 : "Sylop sp. Z o.o. sp.k",
  946 : "Brauns Control GmbH",
  947 : "Omron Corporation",
  948 : "Wildeboer Bauteile Gmbh",
  949 : "Shanghai Biens Technologies Ltd",
  950 : "Beijing HZHY Technology Co., Ltd",
  951 : "Building Clouds",
  952 : "The University of Sheffield-Department of Electronic and Electrical Engineering",
  953 : "Fabtronics Australia Pty Ltd",
  954 : "SLAT",
  955 : "Software Motor Corporation",
  956 : "Armstrong International Inc.",
  957 : "Steril-Aire, Inc.",
  958 : "Infinique",
  959 : "Arcom",
  960 : "Argo Performance, Ltd",
  961 : "Dialight",
  962 : "Ideal Technical Solutions",
  963 : "Neurobat AG",
  964 : "Neyer Software Consulting LLC",
  965 : "SCADA Technology Development Co., Ltd.",
  966 : "Demand Logic Limited",
  967 : "GWA Group Limited",
  968 : "Occitaline",
  969 : "NAO Digital Co., Ltd.",
  970 : "Shenzhen Chanslink Network Technology Co., Ltd.",
  971 : "Samsung Electronics Co., Ltd.",
  972 : "Mesa Laboratories, Inc.",
  973 : "Fischer",
  974 : "OpSys Solutions Ltd.",
  975 : "Advanced Devices Limited",
  976 : "Condair",
  977 : "INELCOM Ingenieria Electronica Comercial S.A.",
  978 : "GridPoint, Inc.",
  979 : "ADF Technologies Sdn Bhd",
  980 : "EPM, Inc.",
  981 : "Lighting Controls Ltd",
  982 : "Perix Controls Ltd.",
  983 : "AERCO International, Inc.",
  984 : "KONE Inc.",
  985 : "Ziehl-Abegg SE",
  986 : "Robot, S.A.",
  987 : "Optigo Networks, Inc.",
  988 : "Openmotics BVBA",
  989 : "Metropolitan Industries, Inc.",
  990 : "Huawei Technologies Co., Ltd.",
  991 : "OSRAM Sylvania, Inc.",
  992 : "Vanti",
  993 : "Cree Lighting",
  994 : "Richmond Heights SDN BHD",
  995 : "Payne-Sparkman Lighting Mangement",
  996 : "Ashcroft",
  997 : "Jet Controls Corp",
  998 : "Zumtobel Lighting GmbH",
  1000 : "Ekon GmbH",
  1001 : "Molex",
  1002 : "Maco Lighting Pty Ltd.",
  1003 : "Axecon Corp.",
  1004 : "Tensor plc",
  1005 : "Kaseman Environmental Control Equipment (Shanghai) Limited",
  1006 : "AB Axis Industries",
  1007 : "Netix Controls",
  1008 : "Eldridge Products, Inc.",
  1009 : "Micronics",
  1010 : "Fortecho Solutions Ltd",
  1011 : "Sellers Manufacturing Company",
  1012 : "Rite-Hite Doors, Inc.",
  1013 : "Violet Defense LLC",
  1014 : "Simna",
  1015 : "Multi-Énergie Best Inc.",
  1016 : "Mega System Technologies, Inc.",
  1017 : "Rheem",
  1018 : "Ing. Punzenberger COPA-DATA GmbH",
  1019 : "MEC Electronics GmbH",
  1020 : "Taco Comfort Solutions",
  1021 : "Alexander Maier GmbH",
  1022 : "Ecorithm, Inc.",
  1023 : "Accurro Ltd",
  1024 : "ROMTECK Australia Pty Ltd",
  1025 : "Splash Monitoring Limited",
  1026 : "Light Application",
  1027 : "Logical Building Automation",
  1028 : "Exilight Oy",
  1029 : "Hager Electro SAS",
  1030 : "KLIF Co., LTD",
  1031 : "HygroMatik",
  1032 : "Daniel Mousseau Programmation & Electronique",
  1033 : "Aerionics Inc.",
  1034 : "M2S Electronique Ltee",
  1035 : "Automation Components, Inc.",
  1036 : "Niobrara Research & Development Corporation",
  1037 : "Netcom Sicherheitstechnik GmbH",
  1038 : "Lumel S.A.",
  1039 : "Great Plains Industries, Inc.",
  1040 : "Domotica Labs S.R.L",
  1041 : "Energy Cloud, Inc.",
  1042 : "Vomatec",
  1043 : "Demma Companies",
  1044 : "Valsena",
  1045 : "Comsys Bärtsch AG",
  1046 : "bGrid",
  1047 : "MDJ Software Pty Ltd",
  1048 : "Dimonoff, Inc.",
  1049 : "Edomo Systems, GmbH",
  1050 : "Effektiv, LLC",
  1051 : "SteamOVap",
  1052 : "grandcentrix GmbH",
  1053 : "Weintek Labs, Inc.",
  1054 : "Intefox GmbH",
  1055 : "Radius22 Automation Company",
  1056 : "Ringdale, Inc.",
  1057 : "Iwaki America",
  1058 : "Bractlet",
  1059 : "STULZ Air Technology Systems, Inc.",
  1060 : "Climate Ready Engineering Pty Ltd",
  1061 : "Genea Energy Partners",
  1062 : "IoTall Chile",
  1063 : "IKS Co., Ltd.",
  1064 : "Yodiwo AB",
  1065 : "TITAN electronic GmbH",
  1066 : "IDEC Corporation",
  1067 : "SIFRI SL",
  1068 : "Thermal Gas Systems Inc.",
  1069 : "Building Automation Products, Inc.",
  1070 : "Asset Mapping",
  1071 : "Smarteh Company",
  1072 : "Datapod Australia Pty Ltd.",
  1073 : "Buildings Alive Pty Ltd",
  1074 : "Digital Elektronik",
  1075 : "Talent Automação e Tecnologia Ltda",
  1076 : "Norposh Limited",
  1077 : "Merkur Funksysteme AG",
  1078 : "Faster CZ spol. S.r.o",
  1079 : "Eco-Adapt",
  1080 : "Energocentrum Plus, s.r.o",
  1081 : "amBX UK Ltd",
  1082 : "Western Reserve Controls, Inc.",
  1083 : "LayerZero Power Systems, Inc.",
  1084 : "CIC Jan Hřebec s.r.o.",
  1085 : "Sigrov BV",
  1086 : "ISYS-Intelligent Systems",
  1087 : "Gas Detection (Australia) Pty Ltd",
  1088 : "Kinco Automation (Shanghai) Ltd.",
  1089 : "Lars Energy, LLC",
  1090 : "Flamefast (UK) Ltd.",
  1091 : "Royal Service Air Conditioning",
  1092 : "Ampio Sp. Z o.o.",
  1093 : "Inovonics Wireless Corporation",
  1094 : "Nvent Thermal Management",
  1095 : "Sinowell Control System Ltd",
  1096 : "Moxa Inc.",
  1097 : "Matrix iControl SDN BHD",
  1098 : "PurpleSwift",
  1099 : "OTIM Technologies",
  1100 : "FlowMate Limited",
  1101 : "Degree Controls, Inc.",
  1102 : "Fei Xing (Shanghai) Software Technologies Co., Ltd.",
  1103 : "Berg GmbH",
  1104 : "ARENZ.IT",
  1105 : "Edelstrom Electronic Devices & Designing LLC",
  1106 : "Drive Connect, LLC",
  1107 : "DevelopNow",
  1108 : "Poort",
  1109 : "VMEIL Information (Shanghai) Ltd",
  1110 : "Rayleigh Instruments",
  1112 : "CODESYS Development",
  1113 : "Smartware Technologies Group, LLC",
  1114 : "Polar Bear Solutions",
  1115 : "Codra",
  1116 : "Pharos Architectural Controls Ltd",
  1117 : "EngiNear Ltd.",
  1118 : "Ad Hoc Electronics",
  1119 : "Unified Microsystems",
  1120 : "Industrieelektronik Brandenburg GmbH",
  1121 : "Hartmann GmbH",
  1122 : "Piscada",
  1123 : "KMB systems, s.r.o.",
  1124 : "PowerTech Engineering AS",
  1125 : "Telefonbau Arthur Schwabe GmbH & Co. KG",
  1126 : "Wuxi Fistwelove Technology Co., Ltd.",
  1127 : "Prysm",
  1128 : "STEINEL GmbH",
  1129 : "Georg Fischer JRG AG",
  1130 : "Make Develop SL",
  1131 : "Monnit Corporation",
  1132 : "Mirror Life Corporation",
  1133 : "Secure Meters Limited",
  1134 : "PECO",
  1135 : ".CCTECH, Inc.",
  1136 : "LightFi Limited",
  1137 : "Nice Spa",
  1138 : "Fiber SenSys, Inc.",
  1139 : "B&D Buchta und Degeorgi",
  1140 : "Ventacity Systems, Inc.",
  1141 : "Hitachi-Johnson Controls Air Conditioning, Inc.",
  1142 : "Sage Metering, Inc.",
  1143 : "Andel Limited",
  1144 : "ECOSmart Technologies",
  1145 : "S.E.T.",
  1146 : "Protec Fire Detection Spain SL",
  1147 : "AGRAMER UG",
  1148 : "Anylink Electronic GmbH",
  1149 : "Schindler, Ltd",
  1150 : "Jibreel Abdeen Est.",
  1151 : "Fluidyne Control Systems Pvt. Ltd",
  1152 : "Prism Systems, Inc.",
  1153 : "Enertiv",
  1154 : "Mirasoft GmbH & Co. KG",
  1155 : "DUALTECH IT",
  1156 : "Countlogic, LLC",
  1157 : "Kohler",
  1158 : "Chen Sen Controls Co., Ltd.",
  1159 : "Greenheck",
  1160 : "Intwine Connect, LLC",
  1161 : "Karlborgs Elkontroll",
  1162 : "Datakom",
  1163 : "Hoga Control AS",
  1164 : "Cool Automation",
  1165 : "Inter Search Co., Ltd",
  1166 : "DABBEL-Automation Intelligence GmbH",
  1167 : "Gadgeon Engineering Smartness",
  1168 : "Coster Group S.r.l.",
  1169 : "Walter Müller AG",
  1170 : "Fluke",
  1171 : "Quintex Systems Ltd",
  1172 : "Senfficient SDN BHD",
  1173 : "Nube iO Operations Pty Ltd",
  1174 : "DAS Integrator Pte Ltd",
  1175 : "CREVIS Co., Ltd",
  1176 : "iSquared software inc.",
  1177 : "KTG GmbH",
  1178 : "POK Group Oy",
  1179 : "Adiscom",
  1180 : "Incusense",
  1181 : "75F",
  1182 : "Anord Mardix, Inc.",
  1183 : "HOSCH Gebäudeautomation Neue Produkte GmbH",
  1184 : "BOSCH Software Innovations GmbH",
  1185 : "Royal Boon Edam International B.V.",
  1186 : "Clack Corporation",
  1187 : "Unitex Controls LLC",
  1188 : "KTC Göteborg AB",
  1189 : "Interzon AB",
  1190 : "ISDE ING SL",
  1191 : "ABM automation building messaging GmbH",
  1192 : "Kentec Electronics Ltd",
  1193 : "Emerson Commercial and Residential Solutions",
  1194 : "Powerside",
  1195 : "SMC Group",
  1196 : "EOS Weather Instruments",
  1197 : "Zonex Systems",
  1198 : "Generex Systems Computervertriebsgesellschaft mbH",
  1199 : "Energy Wall LLC",
  1200 : "Thermofin",
  1201 : "SDATAWAY SA",
  1202 : "Biddle Air Systems Limited",
  1203 : "Kessler Ellis Products",
  1204 : "Thermoscreens",
  1205 : "Modio",
  1206 : "Newron Solutions",
  1207 : "Unitronics",
  1208 : "TRILUX GmbH & Co. KG",
  1209 : "Kollmorgen Steuerungstechnik GmbH",
  1210 : "Bosch Rexroth AG",
  1211 : "Alarko Carrier",
  1212 : "Verdigris Technologies"
}


property_identifier_enum ={
    0 : "acked-transitions",
    1 :"ack-required",
    2 :"action",
    3 : "action-text",
    4 : "active-text" ,
    5 : "active-vt-sessions" ,
    6 : "alarm-value" ,
    7 : "alarm-values" ,
    8 : "all" ,
    9 : "all-writes-successful" ,
    10 : "apdu-segment-timeout" ,
    11 : "apdu-timeout" ,
    12 : "application-software-version" ,
    13 : "archive" ,
    14 : "bias" ,
    15 : "change-of-state-count" ,
    16 : "change-of-state-time" ,
    17 : "notification-class" ,
    18 : " property deleted" ,
    19 : "controlled-variable-reference" ,
    20 : "controlled-variable-units" ,
    21 : "controlled-variable-value" ,
    22 : "cov-increment" ,
    23 : "date-list" ,
    24 : "daylight-savings-status" ,
    25 : "deadband" ,
    26 : "derivative-constant" ,
    27 : "derivative-constant-units" ,
    28 : "description" ,
    29 : "description-of-halt" ,
    30 : "device-address-binding" ,
    31 : "device-type" ,
    32 : "effective-period" ,
    33 : "elapsed-active-time" ,
    34 : "error-limit" ,
    35 : "event-enable" ,
    36 : "event-state" ,
    37 : "event-type" ,
    38 : "exception-schedule" ,
    39 : "fault-values" ,
    40 : "feedback-value" ,
    41 : "file-access-method" ,
    42 : "file-size" ,
    43 : "file-type" ,
    44 : "firmware-revision" ,
    45 : "high-limit" ,
    46 : "inactive-text" ,
    47 : "in-process" ,
    48 : "instance-of" ,
    49 : "integral-constant" ,
    50 : "integral-constant-units" ,
    51 : "issue-confirmed-notifications" ,
    52 : "limit-enable" ,
    53 : "list-of-group-members" ,
    54 : "list-of-object-property-references" ,
    55 : "erly: list-of-session-keys" ,
    56 : "local-date" ,
    57 : "local-time" ,
    58 : "location" ,
    59 : "low-limit" ,
    60 : "manipulated-variable-reference" ,
    61 : "maximum-output" ,
    62 : "max-apdu-length-accepted" ,
    63 : "max-info-frames" ,
    64 : "max-master" ,
    65 : "max-pres-value" ,
    66 : "minimum-off-time" ,
    67 : "minimum-on-time" ,
    68 : "minimum-output" ,
    69 : "min-pres-value" ,
    70 : "model-name" ,
    71 : "modification-date" ,
    72 : "notify-type" ,
    73 : "number-of-apdu-retries" ,
    74 : "number-of-states" ,
    75 : "object-identifier" ,
    76 : "object-list" ,
    77 : "object-name" ,
    78 : "object-property-reference" ,
    79 : "object-type" ,
    80 : "optional" ,
    81 : "out-of-service" ,
    82 : "output-units" ,
    83 : "event-parameters" ,
    84 : "polarity" ,
    85 : "present-value" ,
    86 : "priority" ,
    87 : "priority-array" ,
    88 : "priority-for-writing" ,
    89 : "process-identifier" ,
    90 : "program-change" ,
    91 : "program-location" ,
    92 : "program-state" ,
    93 : "proportional-constant" ,
    94 : "proportional-constant-units" ,
    95 : "erly: protocol-conformance-class" ,
    96 : "protocol-object-types-supported" ,
    97 : "protocol-services-supported" ,
    98 : "protocol-version" ,
    99 : "read-only" ,
    100 : "reason-for-halt" ,
    101 : "erly: recipient" ,
    102 : "recipient-list" ,
    103 : "reliability" ,
    104 : "relinquish-default" ,
    105 : "required" ,
    106 : "resolution" ,
    107 : "segmentation-supported" ,
    108 : "setpoint" ,
    109 : "setpoint-reference" ,
    110 : "state-text" ,
    111 : "status-flags" ,
    112 : "system-status" ,
    113 : "time-delay" ,
    114 : "time-of-active-time-reset" ,
    115 : "time-of-state-count-reset" ,
    116 : "time-synchronization-recipients" ,
    117 : "units" ,
    118 : "update-interval" ,
    119 : "utc-offset" ,
    120 : "vendor-identifier" ,
    121 : "vendor-name" ,
    122 : "vt-classes-supported" ,
    123 : "weekly-schedule" ,
    124 : "attempted-samples" ,
    125 : "average-value" ,
    126 : "buffer-size" ,
    127 : "client-cov-increment" ,
    128 : "cov-resubscription-interval" ,
    129 : "current-notify-time" ,
    130 : "event-time-stamps",
    131 : "log-buffer" ,
    132 : "log-device-object-property" ,
    133 : "enable" ,
    134 : "log-interval" ,
    135 : "maximum-value" ,
    136 : "minimum-value" ,
    137 : "notification-threshold" ,
    138 : "erly: previous-notify-time" ,
    139 : "protocol-revision" ,
    140 : "records-since-notification" ,
    141 : "record-count" ,
    142 : "start-time" ,
    143 : "stop-time" ,
    144 : "stop-when-full" ,
    145 : "total-record-count" ,
    146 : "valid-samples" ,
    147 : "window-interval" ,
    148 : "window-samples" ,
    149 : "maximum-value-timestamp" ,
    150 : "minimum-value-timestamp" ,
    151 : "variance-value" ,
    152 : "active-cov-subscriptions" ,
    153 : "backup-failure-timeout" ,
    154 : "configuration-files" ,
    155 : "database-revision" ,
    156 : "direct-reading" ,
    157 : "last-restore-time," ,
    158 : "maintenance-required" ,
    159 : "member-of" ,
    160 : "mode" ,
    161 : "operation-expected" ,
    162 : "setting" ,
    163 : "silenced" ,
    164 : "tracking-value" ,
    165 : "zone-members" ,
    166 : "life-safety-alarm-values" ,
    167 : "max-segments-accepted" ,
    168 : "profile-name" ,
    169 : "auto-slave-discovery" ,
    170 : "manual-slave-address-binding" ,
    171 : "slave-address-binding" ,
    172 : "slave-proxy-enable" ,
    173 : "last-notify-record" ,
    174 : "schedule-default" ,
    175 : "accepted-modes" ,
    176 : "adjust-value" ,
    177 : "count" ,
    178 : "count-before-change" ,
    179 : "count-change-time" ,
    180 : "cov-period" ,
    181 : "input-reference" ,
    182 : "limit-monitoring-interval" ,
    183 : "logging-object" ,
    184 : "logging-record" ,
    185 : "prescale" ,
    186 : "pulse-rate" ,
    187 : "scale" ,
    188 : "scale-factor" ,
    189 : "update-time" ,
    190 : "value-before-change" ,
    191 : "value-set" ,
    192 : "value-change-time" ,
    193 : "align-intervals" ,
    195 : "interval-offset" ,
    196 : "last-restart-reason" ,
    197 : "logging-type" ,
    202 : "restart-notification-recipients" ,
    203 : "time-of-device-restart" ,
    204 : "time-synchronization-interval" ,
    205 : "trigger" ,
    206 : "utc-time-synchronization-recipients" ,
    207 : "node-subtype" ,
    208 : "node-type" ,
    209 : "structured-object-list" ,
    210 : "subordinate-annotations" ,
    211 : "subordinate-list" ,
    212 : "actual-shed-level" ,
    213 : "duty-window" ,
    214 : "expected-shed-level" ,
    215 : "full-duty-baseline" ,
    218 : "requested-shed-level" ,
    219 : "shed-duration" ,
    220 : "shed-level-descriptions" ,
    221 : "shed-levels" ,
    222 : "state-description" ,
    226 : "door-alarm-state" ,
    227 : "door-extended-pulse-time" ,
    228 : "door-members" ,
    229 : "door-open-too-long-time" ,
    230 : "door-pulse-time" ,
    231 : "door-status" ,
    232 : "door-unlock-delay-time" ,
    233 : "lock-status" ,
    234 : "masked-alarm-values" ,
    235 : "secured-status" ,
    244 : "absentee-limit" ,
    245 : "access-alarm-events" ,
    246 : "access-doors" ,
    247 : "access-event" ,
    248 : "access-event-authentication-factor" ,
    249 : "access-event-credential" ,
    250 : "access-event-time" ,
    251 : "access-transaction-events" ,
    252 : "accompaniment" ,
    253 : "accompaniment-time" ,
    254 : "activation-time" ,
    255 : "active-authentication-policy" ,
    256 : "assigned-access-rights" ,
    257 : "authentication-factors" ,
    258 : "authentication-policy-list" ,
    259 : "authentication-policy-names" ,
    260 : "authentication-status" ,
    261 : "authorization-mode" ,
    262 : "belongs-to" ,
    263 : "credential-disable" ,
    264 : "credential-status" ,
    265 : "credentials" ,
    266 : "credentials-in-zone" ,
    267 : "days-remaining" ,
    268 : "entry-points" ,
    269 : "exit-points" ,
    270 : "expiration-time" ,
    271 : "extended-time-enable" ,
    272 : "failed-attempt-events" ,
    273 : "failed-attempts" ,
    274 : "failed-attempts-time" ,
    275 : "last-access-event" ,
    276 : "last-access-point" ,
    277 : "last-credential-added" ,
    278 : "last-credential-added-time" ,
    279 : "last-credential-removed" ,
    280 : "last-credential-removed-time" ,
    281 : "last-use-time" ,
    282 : "lockout" ,
    283 : "lockout-relinquish-time" ,
    284 : "erly: master-exemption" ,
    285 : "max-failed-attempts" ,
    286 : "members" ,
    287 : "muster-point" ,
    288 : "negative-access-rules" ,
    289 : "number-of-authentication-policies" ,
    290 : "occupancy-count" ,
    291 : "occupancy-count-adjust" ,
    292 : "occupancy-count-enable" ,
    293 : "erly: occupancy-exemption" ,
    294 : "occupancy-lower-limit" ,
    295 : "occupancy-lower-limit-enforced" ,
    296 : "occupancy-state" ,
    297 : "occupancy-upper-limit" ,
    298 : "occupancy-upper-limit-enforced" ,
    299 : "erly: passback-exemption" ,
    300 : "passback-mode" ,
    301 : "passback-timeout" ,
    302 : "positive-access-rules" ,
    303 : "reason-for-disable" ,
    304 : "supported-formats" ,
    305 : "supported-format-classes" ,
    306 : "threat-authority" ,
    307 : "threat-level" ,
    308 : "trace-flag" ,
    309 : "transaction-notification-class" ,
    310 : "user-external-identifier" ,
    311 : "user-information-reference" ,
    317 : "user-name" ,
    318 : "user-type" ,
    319 : "uses-remaining" ,
    320 : "zone-from" ,
    321 : "zone-to" ,
    322 : "access-event-tag" ,
    323 : "global-identifier" ,
    326 : "verification-time" ,
    338 : "backup-and-restore-state" ,
    339 : "backup-preparation-time" ,
    340 : "restore-completion-time" ,
    341 : "restore-preparation-time" ,
    342 : "bit-mask" ,
    343 : "bit-text" ,
    344 : "is-utc" ,
    345 : "group-members" ,
    346 : "group-member-names" ,
    347 : "member-status-flags" ,
    348 : "requested-update-interval" ,
    349 : "covu-period" ,
    350 : "covu-recipients" ,
    351 : "event-message-texts" ,
    352 : "event-message-texts-config" ,
    353 : "event-detection-enable" ,
    354 : "event-algorithm-inhibit" ,
    355 : "event-algorithm-inhibit-ref" ,
    356 : "time-delay-normal" ,
    357 : "reliability-evaluation-inhibit" ,
    358 : "fault-parameters" ,
    359 : "fault-type" ,
    360 : "local-forwarding-only" ,
    361 : "process-identifier-filter" ,
    362 : "subscribed-recipients" ,
    363 : "port-filter" ,
    364 : "authorization-exemptions" ,
    365 : "allow-group-delay-inhibit" ,
    366 : "channel-number" ,
    367 : "control-groups" ,
    368 : "execution-delay" ,
    369 : "last-priority" ,
    370 : "write-status" ,
    371 : "property-list" ,
    372 : "serial-number" ,
    373 : "blink-warn-enable" ,
    374 : "default-fade-time" ,
    375 : "default-ramp-rate" ,
    376 : "default-step-increment" ,
    377 : "egress-time" ,
    378 : "in-progress" ,
    379 : "instantaneous-power" ,
    380 : "lighting-command" ,
    381 : "lighting-command-default-priority" ,
    382 : "max-actual-value" ,
    383 : "min-actual-value" ,
    384 : "power" ,
    385 : "transition" ,
    386 : "egress-active" ,
    387 : "interface-value" ,
    388 : "fault-high-limit" ,
    389 : "fault-low-limit" ,
    390 : "low-diff-limit" ,
    391 : "strike-count" ,
    392 : "time-of-strike-count-reset" ,
    393 : "default-timeout" ,
    394 : "initial-timeout" ,
    395 : "last-state-change" ,
    396 : "state-change-values" ,
    397 : "timer-running" ,
    398 : "timer-state" ,
    399 : "apdu-length" ,
    400 : "ip-address" ,
    401 : "ip-default-gateway" ,
    402 : "ip-dhcp-enable" ,
    403 : "ip-dhcp-lease-time" ,
    404 : "ip-dhcp-lease-time-remaining" ,
    405 : "ip-dhcp-server" ,
    406 : "ip-dns-server" ,
    407 : "bacnet-ip-global-address" ,
    408 : "bacnet-ip-mode" ,
    409 : "bacnet-ip-multicast-address" ,
    410 : "bacnet-ip-nat-traversal" ,
    411 : "ip-subnet-mask" ,
    412 : "bacnet-ip-udp-port" ,
    413 : "bbmd-accept-fd-registrations" ,
    414 : "bbmd-broadcast-distribution-table" ,
    415 : "bbmd-foreign-device-table" ,
    416 : "changes-pending" ,
    417 : "command" ,
    418 : "fd-bbmd-address" ,
    419 : "fd-subscription-lifetime" ,
    420 : "link-speed" ,
    421 : "link-speeds" ,
    422 : "link-speed-autonegotiate" ,
    423 : "mac-address" ,
    424 : "network-interface-name" ,
    425 : "network-number" ,
    426 : "network-number-quality" ,
    427 : "network-type" ,
    428 : "routing-table" ,
    429 : "virtual-mac-address-table" ,
    430 : "command-time-array" ,
    431 : "current-command-priority" ,
    432 : "last-command-time" ,
    433 : "value-source" ,
    434 : "value-source-array" ,
    435 : "bacnet-ipv6-mode" ,
    436 : "ipv6-address" ,
    437 : "ipv6-prefix-length" ,
    438 : "bacnet-ipv6-udp-port" ,
    439 : "ipv6-default-gateway" ,
    440 : "bacnet-ipv6-multicast-address" ,
    441 : "ipv6-dns-server" ,
    442 : "ipv6-auto-addressing-enable" ,
    443 : "ipv6-dhcp-lease-time" ,
    444 : "ipv6-dhcp-lease-time-remaining" ,
    445 : "ipv6-dhcp-server" ,
    446 : "ipv6-zone-index" ,
    447 : "assigned-landing-calls" ,
    448 : "car-assigned-direction" ,
    449 : "car-door-command" ,
    450 : "car-door-status" ,
    451 : "car-door-text" ,
    452 : "car-door-zone" ,
    453 : "car-drive-status" ,
    454 : "car-load" ,
    455 : "car-load-units" ,
    456 : "car-mode" ,
    457 : "car-moving-direction" ,
    458 : "car-position" ,
    459 : "elevator-group" ,
    460 : "energy-meter" ,
    461 : "energy-meter-ref" ,
    462 : "escalator-mode" ,
    463 : "fault-signals" ,
    464 : "floor-text" ,
    465 : "group-id" ,
    467 : "group-mode" ,
    468 : "higher-deck" ,
    469 : "installation-id" ,
    470 : "landing-calls" ,
    471 : "landing-call-control" ,
    472 : "landing-door-status" ,
    473 : "lower-deck" ,
    474 : "machine-room-id" ,
    475 : "making-car-call" ,
    476 : "next-stopping-floor" ,
    477 : "operation-direction" ,
    478 : "passenger-alarm" ,
    479 : "power-mode" ,
    480 : "registered-car-call" ,
    481 : "active-cov-multiple-subscriptions" ,
    482 : "protocol-level" ,
    483 : "reference-port" ,
    484 : "deployed-profile-location" ,
    485 : "profile-location" ,
    486 : "tags" ,
    487 : "subordinate-node-types" ,
    488 : "subordinate-tags" ,
    489 : "subordinate-relationships" ,
    490 : "default-subordinate-relationship" ,
    491 : "represents" ,
    492 : "default-present-value" ,
    493 : "present-stage" ,
    494 : "stages" ,
    495 : "stage-names" ,
    496 : "target-references" ,
    497 : "audit-source-level" ,
    498 : "audit-level" ,
    499 : "audit-notification-recipient" ,
    500 : "audit-priority-filter" ,
    501 : "auditable-operations" ,
    502 : "delete-on-forward" ,
    503 : "maximum-send-delay" ,
    504 : "monitored-objects" ,
    505 : "send-now" ,
    506 : "floor-number" ,
    507 : "device-uuid" ,
}
    
with open("rsc/VendorPropertyMapping.csv", mode='r', encoding='utf-8') as file:
        reader = csv.reader(file)
        next(reader)
        for row in reader:
                property_identifier_enum[int(row[1])] = row[2] + f" ({row[1]})"

event_state = {
 0 : "normal",
 1 : "fault",
 2 : "offnormal",
 3 : "high-limit",
 4 : "low-limit",
 5 : "life-safety-alarm"
}

event_type = {
   0 : "change-of-bitstring",
   1 : "change-of-state",
   2 : "change-of-value",
   3 : "command-failure",
   4 : "floating-limit",
   5 : "out-of-range",
   6 : "complex-event-type",
   8 : "change-of-life-safety",
   9 : "extended",
  10 : "buffer-ready",
  11 : "unsigned-range",
  13 : "access-event",
  14 : "double-out-of-range",
  15 : "signed-out-of-range",
  16 : "unsigned-out-of-range",
  17 : "change-of-characterstring",
  18 : "change-of-status-flags",
  19 : "change-of-reliability",
  20 : "none",
  21 : "change-of-discrete-value",
  22 : "change-of-time"
}

notify_type = {
  0 : "alarm",
  1 : "event",
  2 : "ack-notification"
}

segmentation = {
  0: "segmented-both",
  1: "segmented-transmit",
  2: "segmented-receive",
  3: "no-segmentation"
}

device_status = {
  0 : "operational",
  1 : "operational-read-only",
  2 : "operational-required",
  3 : "operational-in-progress",
  4 : "non-operational",
  5 : "backup-in-progress",
}

error_class= {
  0: "device",
  1: "object",
  2: "property",
  3: "ressource",
  4: "security",
  5: "service",
  6: "VT",
  7: "communication",
  
}

error_code = {
    0: "other",
    2: "configuration-in-progress",
    3: "device-busy",
    4: "dynamic-creation-not-supported",
    5: "file-access-denied",
    7: "inconsistent-parameters",
    8: "inconsistent-selection-criterion",
    9: "invalid-data-type",
    10: "invalid-file-access-method",
    11: "invalid-file-start-position",
    13: "invalid-parameter-data-type",
    14: "invalid-timestamp",
    16: "missing-required-parameter",
    17: "no-objects-of-specified-type",
    18: "no-space-for-object",
    19: "no-space-to-add-list-element",
    20: "no-space-to-write-property",
    21: "no-vt-sessions-available",
    22: "property-is-not-a-list",
    23: "object-deletion-not-permitted",
    24: "object-identifier-already-exists",
    25: "operational-problem",
    26: "password-failure",
    27: "read-access-denied",
    29: "service-request-denied",
    30: "timeout",
    31: "unknown-object",
    32: "unknown-property",
    34: "unknown-vt-class",
    35: "unknown-vt-session",
    36: "unsupported-object-type",
    37: "value-out-of-range",
    38: "vt-session-already-closed",
    39: "vt-session-termination-failure",
    40: "write-access-denied",
    41: "character-set-not-supported",
    42: "invalid-array-index",
    43: "cov-subscription-failed",
    44: "not-cov-property",
    45: "optional-functionality-not-supported",
    46: "invalid-configuration-data",
    47: "datatype-not-supported",
    48: "duplicate-name",
    49: "duplicate-object-id",
    50: "property-is-not-an-array",
    51: "abort-buffer-overflow",
    52: "abort-invalid-apdu-in-this-state",
    53: "abort-preempted-by-higher-priority-task",
    54: "abort-segmentation-not-supported",
    55: "abort-proprietary",
    56: "abort-other",
    57: "invalid-tag",
    58: "network-down",
    59: "reject-buffer-overflow",
    60: "reject-inconsistent-parameters",
    61: "reject-invalid-parameter-data-type",
    62: "reject-invalid-tag",
    63: "reject-missing-required-parameter",
    64: "reject-parameter-out-of-range",
    65: "reject-too-many-arguments",
    66: "reject-undefined-enumeration",
    67: "reject-unrecognized-service",
    68: "reject-proprietary",
    69: "reject-other",
    70: "unknown-device",
    71: "unknown-route",
    72: "value-not-initialized",
    73: "invalid-event-state",
    74: "no-alarm-configured",
    75: "log-buffer-full",
    76: "logged-value-purged",
    77: "no-property-specified",
    78: "not-configured-for-triggered-logging",
    79: "unknown-subscription",
    80: "parameter-out-of-range",
    81: "list-element-not-found",
    82: "busy",
    83: "communication-disabled",
    84: "success",
    85: "access-denied",
    86: "bad-destination-address",
    87: "bad-destination-device-id",
    88: "bad-signature",
    89: "bad-source-address",
    95: "duplicate-message",
    96: "encryption-not-configured",
    97: "encryption-required",
    101: "malformed-message",
    103: "security-not-configured",
    104: "source-security-required",
    106: "unknown-authentication-type",
    110: "not-router-to-dnet",
    111: "router-busy",
    112: "unknown-network-message",
    113: "message-too-long",
    114: "security-error",
    115: "addressing-error",
    116: "write-bdt-failed",
    117: "read-bdt-failed",
    118: "register-foreign-device-failed",
    119: "read-fdt-failed",
    120: "delete-fdt-entry-failed",
    121: "device-busy",
    122: "unknown-file-size",
    123: "abort-apdu-too-long",
    124: "abort-application-exceeded-reply-time",
    125: "abort-out-of-resources",
    126: "abort-tsm-timeout",
    127: "abort-window-size-out-of-range",
    128: "file-full",
    129: "inconsistent-configuration",
    130: "inconsistent-object-type",
    131: "internal-error",
    132: "not-configured",
    133: "out-of-memory",
    134: "value-too-long",
    135: "abort-insufficient-security",
    136: "abort-proprietary",
    137: "duplicate-entry",
    138: "invalid-value-in-this-state",
    139: "invalid-operation-in-this-state",
    140: "list-item-not-numbered",
    141: "list-item-not-timestamped",
    142: "invalid-data-encoding",
    143: "bvlc-function-unknown",
    144: "bvlc-proprietary-function-unknown",
    145: "header-encoding-error",
    146: "header-not-understood",
    147: "message-incomplete",
    148: "not-a-bacnet-sc-hub",
    149: "payload-expected",
    150: "unexpected-data",
    151: "node-duplicate-vmac",
    152: "http-unexpected-response-code",
    153: "http-no-upgrade",
    154: "http-resource-not-local",
    155: "http-proxy-authentication-failed",
    156: "http-response-timeout",
    157: "http-response-syntax-error",
    158: "http-response-value-error",
    159: "http-response-missing-header",
    160: "http-websocket-header-error",
    161: "http-upgrade-required",
    162: "http-upgrade-error",
    163: "http-temporary-unavailable",
    164: "http-not-a-server",
    165: "http-error",
    166: "websocket-scheme-not-supported",
    167: "websocket-unknown-control-message",
    168: "websocket-close-error",
    169: "websocket-closed-by-peer",
    170: "websocket-endpoint-leaves",
    171: "websocket-protocol-error",
    172: "websocket-data-not-accepted",
    173: "websocket-closed-abnormally",
    174: "websocket-data-inconsistent",
    175: "websocket-data-against-policy",
    176: "websocket-frame-too-long",
    177: "websocket-extension-missing",
    178: "websocket-request-unavailable",
    179: "websocket-error",
    180: "tls-client-certificate-error",
    181: "tls-server-certificate-error",
    182: "tls-client-authentication-failed",
    183: "tls-server-authentication-failed",
    184: "tls-client-certificate-expired",
    185: "tls-server-certificate-expired",
    186: "tls-client-certificate-revoked",
    187: "tls-server-certificate-revoked",
    188: "tls-error",
    189: "dns-unavailable",
    190: "dns-name-resolution-failed",
    191: "dns-resolver-failure",
    192: "dns-error",
    193: "tcp-connect-timeout",
    194: "tcp-connection-refused",
    195: "tcp-closed-by-local",
    196: "tcp-closed-other",
    197: "tep-error",
    198: "ip-address-not-reachable",
    199: "ip-error"
}

reliability = {
   0 : "no-fault-detected",
   1 : "no-sensor",
   2 : "over-range",
   3 : "under-range",
   4 : "open-loop",
   5 : "shorted-loop",
   6 : "no-output",
   7 : "unreliable-other",
   8 : "process-error",
   9 : "multi-state-fault",
  10 : "configuration-error",
  12 : "communication-failure",
  13 : "member-fault",
  14 : "monitored-object-fault",
  15 : "tripped",
  16 : "lamp-failure",
  17 : "activation-failure",
  18 : "renew-dhcp-failure",
  19 : "renew-fd-registration-failure",
  20 : "restart-auto-negotiation-failure",
  21 : "restart-failure",
  22 : "proprietary-command-failure",
  23 : "faults-listed",
  24 : "referenced-object-fault",
  25 : "multi-state-out-of-range",
  
}

days_of_week = {
  0 : "monday",
  1 : "tuesday",
  2 : "wednesday",
  3 : "thursday",
  4 : "friday",
  5 : "saturday",
  6 : "sunday",
}

loggingType = {
  0 : "polled",
  1 : "cov",
  2 : "triggered"
}

reinitialize_device_enum = {
  0 : "coldstart",
  1 : "warmstart",
  2 : "start-backup",
  3 : "end-backup",
  4 : "start-restore",
  5 : "end-restore",
  6 : "abort-restore",
  7 : "activate-changes"
}

restart_reason = {
  0 : "unknown",
  1 : "coldstart",
  2 : "warmstart",
  3 : "detected-power-lost",
  4 : "detected-powered-off",
  5 : "hardware-watchdog",
  6 : "software-watchdog",
  7 : "suspended",
  8 : "activate-changes"
}

engineering_units = {
   0 : "square-meters2",
   1 : "square-feet2",
   2 : "milliamperes2",
   3 : "amperes2",
   4 : "ohms2",
   5 : "volts2",
   6 : "kilovolts2",
   7 : "megavolts2",
   8 : "volt-amperes2",
   9 : "kilovolt-amperes2",
  10 : "megavolt-amperes",
  11 : "volt-amperes-reactive",
  12 : "kilovolt-amperes-reactive",
  13 : "megavolt-amperes-reactive",
  14 : "degrees-phase",
  15 : "power-factor",
  16 : "joules",
  17 : "kilojoules",
  18 : "watt-hours",
  19 : "kilowatt-hours",
  20 : "btus",
  21 : "therms",
  22 : "ton-hours",
  23 : "joules-per-kilogram-dry-air",
  24 : "btus-per-pound-dry-air",
  25 : "cycles-per-hour",
  26 : "cycles-per-minute",
  27 : "hertz",
  28 : "grams-of-water-per-kilogram",
  29 : "percent-relative-humidity",
  30 : "millimeters",
  31 : "meters",
  32 : "inches",
  33 : "feet",
  34 : "watts-per-square-foot",
  35 : "watts-per-square-meter",
  36 : "lumens",
  37 : "luxes",
  38 : "foot-candles",
  39 : "kilograms",
  40 : "pounds-mass",
  41 : "tons",
  42 : "kilograms-per-second",
  43 : "kilograms-per-minute",
  44 : "kilograms-per-hour",
  45 : "pounds-mass-per-minute",
  46 : "pounds-mass-per-hour",
  47 : "watts",
  48 : "kilowatts",
  49 : "megawatts",
  50 : "btus-per-hour",
  51 : "horsepower",
  52 : "tons-refrigeration",
  53 : "pascals",
  54 : "kilopascals",
  55 : "bars",
  56 : "pounds-force-per-square-inch",
  57 : "centimeters-of-water",
  58 : "inches-of-water",
  59 : "millimeters-of-mercury",
  60 : "centimeters-of-mercury",
  61 : "inches-of-mercury",
  62 : "degrees-celsius",
  63 : "degrees-kelvin",
  64 : "degrees-fahrenheit",
  65 : "degree-days-celsius",
  66 : "degree-days-fahrenheit",
  67 : "years",
  68 : "months",
  69 : "weeks",
  70 : "days",
  71 : "hours",
  72 : "minutes",
  73 : "seconds",
  74 : "meters-per-second",
  75 : "kilometers-per-hour",
  76 : "feet-per-second",
  77 : "feet-per-minute",
  78 : "miles-per-hour",
  79 : "cubic-feet",
  80 : "cubic-meters",
  81 : "imperial-gallons",
  82 : "liters",
  83 : "us-gallons",
  84 : "cubic-feet-per-minute",
  85 : "cubic-meters-per-second",
  86 : "imperial-gallons-per-minute",
  87 : "liters-per-second",
  88 : "liters-per-minute",
  89 : "us-gallons-per-minute",
  90 : "degrees-angular",
  91 : "degrees-celsius-per-hour",
  92 : "degrees-celsius-per-minute",
  93 : "degrees-fahrenheit-per-hour",
  94 : "degrees-fahrenheit-per-minute",
  95 : "no-units",
  96 : "parts-per-million",
  97 : "parts-per-billion",
  98 : "percent",
  99 : "percent-per-second",
  100 : "per-minute",
  101 : "per-second",
  102 : "psi-per-degree-fahrenheit",
  103 : "radians",
  104 : "revolutions-per-minute",
  105 : "currency1",
  106 : "currency2",
  107 : "currency3",
  108 : "currency4",
  109 : "currency5",
  110 : "currency6",
  111 : "currency7",
  112 : "currency8",
  113 : "currency9",
  114 : "currency10",
  115 : "square-inches",
  116 : "square-centimeters",
  117 : "btus-per-pound",
  118 : "centimeters",
  119 : "pounds-mass-per-second",
  120 : "delta-degrees-fahrenheit",
  121 : "delta-degrees-kelvin",
  122 : "kilohms",
  123 : "megohms",
  124 : "millivolts",
  125 : "kilojoules-per-kilogram",
  126 : "megajoules",
  127 : "joules-per-degree-kelvin",
  128 : "joules-per-kilogram-degree-kelvin",
  129 : "kilohertz",
  130 : "megahertz",
  131 : "per-hour",
  132 : "milliwatts",
  133 : "hectopascals",
  134 : "millibars",
  135 : "cubic-meters-per-hour",
  136 : "liters-per-hour",
  137 : "kilowatt-hours-per-square-meter",
  138 : "kilowatt-hours-per-square-foot",
  139 : "megajoules-per-square-meter",
  140 : "megajoules-per-square-foot",
  141 : "watts-per-square-meter-degree-kelvin",
  142 : "cubic-feet-per-second",
  143 : "percent-obscuration-per-foot",
  144 : "percent-obscuration-per-meter",
  145 : "milliohms",
  146 : "megawatt-hours",
  147 : "kilo-btus",
  148 : "mega-btus",
  149 : "kilojoules-per-kilogram-dry-air",
  150 : "megajoules-per-kilogram-dry-air",
  151 : "kilojoules-per-degree-kelvin",
  152 : "megajoules-per-degree-kelvin",
  153 : "newton",
  154 : "grams-per-second",
  155 : "grams-per-minute",
  156 : "tons-per-hour",
  157 : "kilo-btus-per-hour",
  158 : "hundredths-seconds",
  159 : "milliseconds",
  160 : "newton-meters",
  161 : "millimeters-per-second",
  162 : "millimeters-per-minute",
  163 : "meters-per-minute",
  164 : "meters-per-hour",
  165 : "cubic-meters-per-minute",
  166 : "meters-per-second-per-second",
  167 : "amperes-per-meter",
  168 : "amperes-per-square-meter",
  169 : "ampere-square-meters",
  170 : "farads",
  171 : "henrys",
  172 : "ohm-meters",
  173 : "siemens",
  174 : "siemens-per-meter",
  175 : "teslas",
  176 : "volts-per-degree-kelvin",
  177 : "volts-per-meter",
  178 : "webers",
  179 : "candelas",
  180 : "candelas-per-square-meter",
  181 : "degrees-kelvin-per-hour",
  182 : "degrees-kelvin-per-minute",
  183 : "joule-seconds",
  184 : "radians-per-second",
  185 : "square-meters-per-newton",
  186 : "kilograms-per-cubic-meter",
  187 : "newton-seconds",
  188 : "newtons-per-meter",
  189 : "watts-per-meter-per-degree-kelvin",
  190 : "micro-siemens",
  191 : "cubic-feet-per-hour",
  192 : "us-gallons-per-hour",
  193 : "kilometers",
  194 : "micrometers",
  195 : "grams",
  196 : "milligrams",
  197 : "milliliters",
  198 : "milliliters-per-second",
  199 : "decibels",
  200 : "decibels-millivolt",
  201 : "decibels-volt",
  202 : "millisiemens",
  203 : "watt-hours-reactive",
  204 : "kilowatt-hours-reactive",
  205 : "megawatt-hours-reactive",
  206 : "millimeters-of-water",
  207 : "per-mille",
  208 : "grams-per-gram",
  209 : "kilograms-per-kilogram",
  210 : "grams-per-kilogram",
  211 : "milligrams-per-gram",
  212 : "milligrams-per-kilogram",
  213 : "grams-per-milliliter",
  214 : "grams-per-liter",
  215 : "milligrams-per-liter",
  216 : "micrograms-per-liter",
  217 : "grams-per-cubic-meter",
  218 : "milligrams-per-cubic-meter",
  219 : "micrograms-per-cubic-meter",
  220 : "nanograms-per-cubic-meter",
  221 : "grams-per-cubic-centimeter",
  222 : "becquerels",
  223 : "kilobecquerels",
  224 : "megabecquerels",
  225 : "gray",
  226 : "milligray",
  227 : "microgray",
  228 : "sieverts",
  229 : "millisieverts",
  230 : "microsieverts",
  231 : "microsieverts-per-hour",
  232 : "decibels-a",
  233 : "nephelometric-turbidity-unit",
  234 : "pH",
  235 : "grams-per-square-meter",
  236 : "minutes-per-degree-kelvin",
  237 : "ohm-meter-squared-per-meter",
  238 : "ampere-seconds",
  239 : "volt-ampere-hours",
  240 : "kilovolt-ampere-hours",
  241 : "megavolt-ampere-hours",
  242 : "volt-ampere-hours-reactive",
  243 : "kilovolt-ampere-hours-reactive",
  244 : "megavolt-ampere-hours-reactive",
  245 : "volt-square-hours",
  246 : "ampere-square-hours",
  247 : "joule-per-hours",
  248 : "cubic-feet-per-day",
  249 : "cubic-meters-per-day",
  250 : "watt-hours-per-cubic-meter",
  251 : "joules-per-cubic-meter",
  252 : "mole-percent",
  253 : "pascal-seconds",
  254 : "million-standard-cubic-feet-per-minute",
 47808 : "standard-cubic-feet-per-day",
 47809 : "million-standard-cubic-feet-per-day",
 47810 : "thousand-cubic-feet-per-day",
 47811 : "thousand-standard-cubic-feet-per-day",
 47812 : "pounds-mass-per-day",
 47814 : "millirems",
 47815 : "millirems-per-hour",
 47816 : "degrees-lovibond",
 47817 : "alcohol-by-volume",
 47818 : "international-bittering-units",
 47819 : "european-bitterness-units",
 47820 : "degrees-plato",
 47821 : "specific-gravity",
 47822 : "european-brewing-convention",
}

relationships = {
   0 : "unknown",
   1 : "default",
   2 : "contains",
   3 : "contained-by",
   4 : "uses",
   5 : "used-by",
   6 : "commands",
   7 : "commanded-by",
   8 : "adjusts",
   9 : "adjusted-by",
  10 : "ingress",
  11 : "egress",
  12 : "supplies-air",
  13 : "receives-air",
  14 : "supplies-hot-air",
  15 : "receives-hot-air",
  16 : "supplies-cool-air",
  17 : "receives-cool-air",
  18 : "supplies-power",
  19 : "receives-power",
  20 : "supplies-gas",
  21 : "receives-gas",
  22 : "supplies-water",
  23 : "receives-water",
  24 : "supplies-hot-water",
  25 : "receives-hot-water",
  26 : "supplies-cool-water",
  27 : "receives-cool-water",
  28 : "supplies-steam",
  29 : "receives-steam",
}

node_type = {
   0 : "unknown",
   1 : "system",
   2 : "network",
   3 : "device",
   4 : "organizational",
   5 : "area",
   6 : "equipment",
   7 : "point",
   8 : "collection",
   9 : "property",
   0 : "functional ",
  11 : "other",
  12 : "subsystem",
  13 : "building",
  14 : "floor",
  15 : "section",
  16 : "module",
  17 : "tree",
  18 : "member",
  19 : "protocol",
  20 : "room",
  21 : "zone",
}

lighting_transition = {
  0 : "none",
  1 : "fade",
  2 : "ramp"
}

lighting_in_progress = {
  0 : "idle",
  1 : "fade-active",
  2 : "ramp-active",
  3 : "not-controlled",
  4 : "other"
}

lighting_operation = {
  0 : "none",
  1 : "fade",
  2 : "ramp-to",
  3 : "step-up",
  4 : "step-down",
  5 : "step-on",
  6 : "step-off",
  7 : "warn",
  8 : "warn-off",
  9 : "warn-relinquish",
  10 : "stop",
}
binary_lighting_pv = {
  0 : "off",
  1 : "on",
  2 : "warn",
  3 : "warn-off",
  4 : "warn-relinquish",
  5 : "stop",
}



write_status = {
  0 : "idle",
  1 : "in-progress",
  2 : "successful",
  3 : "failed"
}

lifesafety_mode= {
   0 : "off",
   1 : "on",
   2 : "test",
   3 : "manned",
   4 : "unmanned",
   5 : "armed",
   6 : "disarmed",
   7 : "prearmed",
   8 : "slow",
   9 : "fast",
  10 : "disconnected",
  11 : "enabled",
  12 : "disabled",
  13 : "automatic-release-disable",
  14 : "default",
  15 : "activated-oeo-alarm",
  16 : "activated-oeo-evacuate",
  17 : "activated-oeo-phase1-recall",
  18 : "activated-oeo-unavailable",
  19 : "deactivated",
}

lifesafety_state= {
   0 : "quiet",
   1 : "pre-alarm",
   2 : "alarm",
   3 : "fault",
   4 : "fault-pre-alarm",
   5 : "fault-alarm",
   6 : "not-ready",
   7 : "active",
   8 : "tamper",
   9 : "test-alarm",
  10 : "test-active",
  11 : "test-fault",
  12 : "test-fault-alarm",
  13 : "holdup",
  14 : "duress",
  15 : "tamper-alarm",
  16 : "abnormal",
  17 : "emergency-power",
  18 : "delayed",
  19 : "blocked",
  20 : "local-alarm",
  21 : "general-alarm",
  22 : "supervisory",
  23 : "test-supervisory",
  24 : "non-default-mode",
  25 : "oeo-unavailable",
  26 : "oeo-alarm",
  27 : "oeo-phase1-recall",
  28 : "oeo-evacuate",
  29 : "oeo-unaffected",
  30 : "test-oeo-unavailable",
  31 : "test-oeo-alarm",
  32 : "test-oeo-phase1-recall",
  33 : "test-oeo-evacuate",
  34 : "test-oeo-unaffected",
}

lifesafety_operation= {
  0 :"none",
  1 :"silence",
  2 :"silence-audible",
  3 :"silence-visual",
  4 :"reset",
  5 :"reset-alarm",
  6 :"reset-fault",
  7 :"unsilence",
  8 :"unsilence-audible",
  9 :"unsilence-visual",
}

silence_state = {
  0 : "unsilenced",
  1 : "audible-silenced",
  2 : "visible-silenced",
  3 : "all-silenced"
}

protocol_level ={
    0 : "physical",
    1 : "protocol",
    2 : "bacnet-application",
    3 : "non-bacnet-application"
}
network_type = {
  0 : "ethernet",
  1 : "arcnet",
  2 : "mstp",
  3 : "ptp",
  4 : "lontalk",
  5 : "ipv4",
  6 : "zigbee",
  7 : "virtual",
  8 : "non-bacnet",
  9 : "ipv6",
 10 : "serial" 
}
network_number_quality = {
  0 : "unknown",
  1 : "learned",
  2 : "learned-configured",
  3 : "configured"
}

network_port_command = {
  0 : "idle",
  1 : "discard-changes",
  2 : "renew-fd-registration",
  3 : "restart-slave-discovery",
  4 : "renew-dhcp",
  5 : "restart-autonegotiation",
  6 : "disconnect",
  7 : "restart-port",
}

status_flags ={
    0 : "in-alarm",
    1 : "fault",
    2 : "overriden",
    3 : "out-of-service"
}

ip_mode = {
  0 : "normal",
  1 : "foreign",
  2 : "bbmd"
}

access_credential_disable = {
  0 : "none",
  1 : "disable",
  2 : "disable-manual",
  3 : "disable-lockout"
}

access_credential_disable_reason = {
  0 : "disabled",
  1 : "disabled-needs-provisioning",
  2 : "disabled-unassigned",
  3 : "disabled-not-yet-active",
  4 : "disabled-expired",
  5 : "disabled-lockout",
  6 : "disabled-max-days",
  7 : "disabled-max-uses",
  8 : "disabled-inactivity",
  9 : "disabled-manual",
}

access_event = {
   0 : "none",
   1 : "granted",
   2 : "muster",
   3 : "passback-detected",
   4 : "duress",
   5 : "trace",
   6 : "lockout-max-attempts",
   7 : "lockout-other",
   8 : "lockout-relinquished",
   9 : "locked-by-higher-priority",
  10 : "out-of-service",
  11 : "out-of-service-relinquished",
  12 : "accompaniment-by",
  13 : "authentication-factor-read",
  14 : "authorization-delayed",
  15 : "verification-required",
  16 : "no-entry-after-granted",
  128 : "denied-deny-all",
  129 : "denied-unknown-credential",
  130 : "denied-authentication-unavailable",
  131 : "denied-authentication-factor-timeout",
  132 : "denied-incorrect-authentication-factor",
  133 : "denied-zone-no-access-rights",
  134 : "denied-point-no-access-rights",
  135 : "denied-no-access-rights",
  136 : "denied-out-of-time-range",
  137 : "denied-threat-level",
  138 : "denied-passback",
  139 : "denied-unexpected-location-usage",
  140 : "denied-max-attempts",
  141 : "denied-lower-occupancy-limit",
  142 : "denied-upper-occupancy-limit",
  143 : "denied-authentication-factor-lost",
  144 : "denied-authentication-factor-stolen",
  145 : "denied-authentication-factor-damaged",
  146 : "denied-authentication-factor-destroyed",
  147 : "denied-authentication-factor-disabled",
  148 : "denied-authentication-factor-error",
  149 : "denied-credential-unassigned",
  150 : "denied-credential-not-provisioned",
  151 : "denied-credential-not-yet-active",
  152 : "denied-credential-expired",
  153 : "denied-credential-manual-disable",
  154 : "denied-credential-lockout",
  155 : "denied-credential-max-days",
  156 : "denied-credential-max-uses",
  157 : "denied-credential-inactivity",
  158 : "denied-credential-disabled",
  159 : "denied-no-accompaniment",
  160 : "denied-incorrect-accompaniment",
  161 : "denied-lockout",
  162 : "denied-verification-failed",
  163 : "denied-verification-timeout",
  164 : "denied-other",
}

passback_mode ={
  0 : "passback-off",
  1 : "hard-passback",
  2 : "soft-passback"
}

access_user_type = {
  0 : "asset",
  1 : "group",
  2 : "person"
}

access_zone_occupancy_state = {
  0 : "normal",
  1 : "below-lower-limit",
  2 : "at-lower-limit",
  3 : "at-upper-limit",
  4 : "above-upper-limit",
  5 : "disabled",
  6 : "not-supported",
}

action = {
  0 : "direct",
  1 : "reverse"
}

audit_level= {
  0 : "none",
  1 : "audit-all",
  2 : "audit-config",
  3 : "default",
}

audit_operation = {
   0 : "read",
   1 : "write",
   2 : "create",
   3 : "delete",
   4 : "life-safety",
   5 : "acknowledge-alarm",
   6 : "device-disable-comm",
   7 : "device-enable-comm",
   8 : "device-reset",
   9 : "device-backup",
  10 : "device-restore",
  11 : "subscription",
  12 : "notification",
  13 : "auditing-failure",
  14 : "network-changes",
  15 : "general",
}

authentication_status = {
  0 : "not-ready",
  1 : "ready",
  2 : "disabled",
  3 : "waiting-for-authentication-factor",
  4 : "waiting-for-accompaniment",
  5 : "waiting-for-verification",
  6 : "in-progress",
}

authentication_factor_type = {
   0 : "undefined",
   1 : "error",
   2 : "custom",
   3 : "simple-number16",
   4 : "simple-number32",
   5 : "simple-number56",
   6 : "simple-alpha-numeric",
   7 : "aba-track2",
   8 : "wiegand26",
   9 : "wiegand37",
  10 : "wiegand37-facility",
  11 : "facility16-card32",
  12 : "facility32-card32",
  13 : "fasc-n",
  14 : "fasc-n-bcd",
  15 : "fasc-n-large",
  16 : "fasc-n-large-bcd",
  17 : "gsa75",
  18 : "chuid",
  19 : "chuid-full",
  20 : "guid",
  21 : "cbeff-a",
  22 : "cbeff-b",
  23 : "cbeff-c",
  24 : "user-password",
}

authorization_exemption = {
  0 : "passback",
  1 : "occupancy-check",
  2 : "access-rights",
  3 : "lockout",
  4 : "deny",
  5 : "verification",
  6 : "authorization-delay",
}

authorization_mode = {
  0 : "authorize",
  1 : "grant-active",
  2 : "deny-all",
  3 : "verification-required",
  4 : "authorization-delayed",
  5 : "none",
}

backup_state = {
  0 : "idle",
  1 : "preparing-for-backup",
  2 : "preparing-for-restore",
  3 : "performing-a-backup",
  4 : "performing-a-restore",
  5 : "backup-failure",
  6 : "restore-failure",
}

door_alarm_state = {
  0 : "normal",
  1 : "alarm",
  2 : "door-open-too-long",
  3 : "forced-open",
  4 : "tamper",
  5 : "door-fault",
  6 : "lock-down",
  7 : "free-access",
  8 : "egress-open",
}

door_secured_status = {
  0 : "secured",
  1 : "unsecured",
  2 : "unknown"
}

door_status = {
  0 : "closed",
  1 : "opened",
  2 : "unknown",
  3 : "door-fault",
  4 : "unused",
  5 : "none",
  6 : "closing",
  7 : "opening",
  8 : "safety-locked",
  9 : "limited-opened",
}

door_value = {
  0 : "lock",
  1 : "unlock",
  2 : "pulse-unlock",
  3 : "extended-pulse-unlock"
}

escalator_mode = {
  0 : "unknown",
  1 : "stop",
  2 : "up",
  3 : "down",
  4 : "inspection",
  5 : "out-of-service",
}

escalator_operation_direction ={
  0 : "unknown",
  1 : "stopped",
  2 : "up-rated-speed",
  3 : "up-reduced-speed",
  4 : "down-rated-speed",
  5 : "down-reduced-speed",
}

escalator_fault = {
  0 : "ontroller-fault",
  1 : "drive-and-motor-fault",
  2 : "mechanical-component-fault",
  3 : "overspeed-fault",
  4 : "power-supply-fault",
  5 : "safety-device-fault",
  6 : "controller-supply-fault",
  7 : "drive-temperature-exceeded",
  8 : "comb-plate-fault",
}

fault_type ={
  0 : "none",
  1 : "fault-characterstring",
  2 : "fault-extended",
  3 : "fault-life-safety",
  4 : "fault-state",
  5 : "fault-status-flags",
  6 : "fault-out-of-range",
  7 : "fault-listed",
}

file_access_method = {
  0 : "record-access",
  1 : "stream-access"
}

lift_car_direction = {
  0 : "unknown",
  1 : "none",
  2 : "stopped",
  3 : "up",
  4 : "down",
  5 : "up-and-down",
} 

lift_car_door_command = {
  0 : "none",
  1 : "open",
  2 : "close",
} 

lift_car_drive_status = {
  0 : "unknown",
  1 : "stationary",
  2 : "braking",
  3 : "accelerate",
  4 : "decelerate",
  5 : "rated-speed",
  6 : "single-floor-jump",
  7 : "two-floor-jump",
  8 : "three-floor-jump",
  9 : "multi-floor-jump",
}

lift_car_mode = {
   0 : "unknown",
   1 : "normal",
   2 : "vip",
   3 : "homing",
   4 : "parking",
   5 : "attendant-control",
   6 : "firefighter-control",
   7 : "emergency-power",
   8 : "inspection",
   9 : "cabinet-recall",
  10 : "earthquake-operation",
  11 : "fire-operation",
  12 : "out-of-service",
  13 : "occupant-evacuation",
}

lift_fault = {
   0 : "controller-fault",
   1 : "drive-and-motor-fault",
   2 : "governor-and-safety-gear-fault",
   3 : "lift-shaft-device-fault",
   4 : "power-supply-fault",
   5 : "safety-interlock-fault",
   6 : "door-closing-fault",
   7 : "door-opening-fault",
   8 : "car-stopped-outside-landing-zone",
   9 : "call-button-stuck",
   0 : "start-failure ",
  11 : "controller-supply-fault",
  12 : "self-test-failure",
  13 : "runtime-limit-exceeded",
  14 : "position-lost",
  15 : "drive-temperature-exceeded",
  16 : "load-measurement-fault",
}

lift_group_mode = {
  0 : "unknown",
  1 : "normal",
  2 : "down-peak",
  3 : "two-way",
  4 : "four-way",
  5 : "emergency-power",
  6 : "up-peak",
}

lock_status = {
  0 : "locked",
  1 : "unlocked",
  2 : "lock-fault",
  3 : "unused",
  4 : "unknown"
}

maintenance = {
  0 : "none",
  1 : "periodic-test",
  2 : "need-service-operational",
  3 : "need-service-inoperative",
}

program_error = {
  0 : "normal",
  1 : "load-failed",
  2 : "internal",
  3 : "program",
  4 : "other",
}

program_request = {
  0 : "ready",
  1 : "load",
  2 : "run",
  3 : "halt",
  4 : "restart",
  5 : "unload",
}

program_state = {
  0 : "idle",
  1 : "loading",
  2 : "running",
  3 : "waiting",
  4 : "halted",
  5 : "unloading",
}
timer_state = {
  0 : "idle",
  1 : "running",
  2 : "expired"
}

timer_transition = {
  0 : "none",
  1 : "idle-to-running",
  2 : "running-to-idle",
  3 : "running-to-running",
  4 : "running-to-expired",
  5 : "forced-to-expired",
  6 : "expired-to-idle",
  7 : "expired-to-running",
}

vt_class = {
  0 : "default-terminal",
  1 : "ansi-x3-64",
  2 : "dec-vt52",
  3 : "dec-vt100",
  4 : "dec-vt220",
  5 : "hp-700-94",
  6 : "ibm-3130",
}

polarity = {
  0 : "normal",
  1 : "reverse"
}

binary_pv = {
  0 : "inactive",
  1 : "active"
}

shed_state = {
  0: "shed-inactive",
  1: "shed-request-pending",
  2: "shed-compliant",
  3: "shed-non-compliant",
}

specifier = {
   0 : "specified",
   1 : "always"
}

accumulator_status = {
  0 : "normal",
  1 : "starting",
  2 : "recovered",
  3 : "abnormal",
  4 : "failed"
}

access_authentication_factor_disable = {
  0 : "none",
  1 : "disabled",
  2 : "disabled-lost",
  3 : "disabled-stolen",
  4 : "disabled-damaged",
  5 : "disabled-destroyed",
}


enum_by_property = {
  "event-state" : event_state,
  "notify-type" : notify_type,
  "object-type" : object_types,
  "fault-type" :  fault_type,
  "status-flags" : status_flags,
  "segmentation-supported" : segmentation,
  "system-status" : device_status,
  "reliability" : reliability,
  "logging-type" : loggingType,
  "property-list" : property_identifier_enum,
  "units" :  engineering_units,
  "default-subordinate-relationship" : relationships,
  "subordinate-relationships" : relationships,
  "subordinate-node-types" : node_type,
  "node-type" : node_type,
  "transition" : lighting_transition,
  "in-progress" : lighting_in_progress,
  "write-status" : write_status,
  "accepted-modes" : lifesafety_mode,
  "mode" : lifesafety_mode,
  "tracking-value" : lifesafety_state,
  "silenced" : silence_state,
  "operation-expected" : lifesafety_operation,
  "protocol-level" : protocol_level,
  "network-type" : network_type,
  "network-number-quality" : network_number_quality,
  "command" : network_port_command,
  "bacnet-ip-mode" : ip_mode,
  "bacnet-ipv6-mode" : ip_mode,
  "credential-disable" : access_credential_disable,
  "access-event" : access_event,
  "last-access_event" : access_event,
  "passback-mode" : passback_mode,
  "user-type" : access_user_type,
  "occupancy-state" : access_zone_occupancy_state,
  "audit-level" : audit_level,
  "authentication-status" : authentication_status,
  "authorization-exemptions" : authorization_exemption,
  "authorization_mode" : authorization_mode,
  "backup-and-restore-state" : backup_state,
  "door-alarm-state" : door_alarm_state,
  "relinquish-default" : door_value,
  "secured-status" : door_secured_status,
  "door-status" : door_status,
  "car-door-status" : door_status,
  "escalator-mode" : escalator_mode,
  "operation-direction" : escalator_operation_direction,
  "event-type" : event_type,
  "file-access-method" : file_access_method,
  "car-moving-direction" : lift_car_direction,
  "car-door-command" : lift_car_door_command,
  "car-drive-status" : lift_car_drive_status,
  "car-mode" : lift_car_mode,
  "group-mode" : lift_group_mode,
  "lock-status" : lock_status,
  "maintenance-required" : maintenance,
  "reason-for-halt" : program_error,
  "program-change" : program_request,
  "program-state" : program_state,
  "timer-state" : timer_state,
  "last-state-change" :  timer_transition,
  "vt-classes-supported" : vt_class,
  "polarity" : polarity,
  "controlled-variable-units" : engineering_units,
  "derivative-constant-units" : engineering_units,
  "integral-constant-units" : engineering_units,
  "output-units" : engineering_units,
  "proportional-constant-units" : engineering_units,
  "fault-signals" : escalator_fault, 

  "alarm-value" : binary_pv,
  "life-safety-alarm-values" :lifesafety_state,
}

present_value_type = {
  "binary-input" : binary_pv,
  "binary-output" : binary_pv,
  "binary-value" : binary_pv,
  "life-safety-point" : lifesafety_state,
  "life-safety-zone" : lifesafety_state,
  "access-door" : door_value,
  "load-control" :  shed_state,
  "binary-lighting-output" : binary_lighting_pv,
  "credential-data-input" : authentication_factor_type
}

feedback_value_type = {
  "binary-output" : binary_pv,
  "binary-lighting-output" : binary_lighting_pv
}

action_type = {
  "loop" : action,
  "command" :  property_identifier_enum
}

alarm_values_type = {
  "life-safety-point" :lifesafety_state,
  "life-safety-zone" : lifesafety_state,
  "access-door" : door_alarm_state,
  "access-zone" : access_zone_occupancy_state,
  "timer" : timer_state,
}

fault_values_type = {
  "life-safety-point" :lifesafety_state,
  "life-safety-zone" : lifesafety_state,
  "access-door" : door_alarm_state,
  "assigned-landing-calls" : lift_car_direction
}

def get_enum_by_property_and_object(prop : str, obj_type : str):
  '''Get the appropriate enum corresponding to the object and property'''
  if prop == "present-value":
    return present_value_type.get(obj_type,{})
  elif prop == "feedback-value":
    return feedback_value_type.get(obj_type,{})
  elif prop == "action":
    return action_type.get(obj_type,{})
  elif prop == "alarm-values":
    return alarm_values_type.get(obj_type,{})
  elif prop == "fault-values":
    return fault_values_type.get(obj_type,{})
  else:
    return enum_by_property.get(prop,{})
    